### ISSUE TITLE
** Hostname localhost is illegal **

### ISSUE THREAD

**Issue by merdiano** [esl/MongooseIM#2766] opened 2020-05-29 13:20 UTC
MongooseIM version: 3.7.0
Installed from: pkg
Erlang/OTP version: 22

Describe the issue. 
System not running with vm.args contain fqdn using -name
and mongooseim.cfg contain the domain too
Logs
Erlang/OTP 22 [erts-10.7.2.1] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [hipe]
13:12:33.921 [info] msg: "Starting reporters with []\n", options: []
13:12:34.091 [error] ** System running to use fully qualified hostnames **
** Hostname localhost is illegal **
13:12:34.254 [notice] Changed loglevel of /var/log/mongooseim/ejabberd.log to info
13:12:34.300 [info] Application mnesia exited with reason: stopped
13:12:34.317 [error] ** System running to use fully qualified hostnames **
** Hostname localhost is illegal **
13:12:34.800 [error] CRASH REPORT Process <0.351.0> with 0 neighbours exited with reason: no match of right hand va
lue {error,einval} in ejabberd_listener:parse_listener_portip/2 line 122 in application_master:init/4 line 138
13:12:34.802 [info] Application mongooseim exited with reason: no match of right hand value {error,einval} in ejabb
erd_listener:parse_listener_portip/2 line 122

**Comment by fenek** [comment] 2020-05-29 13:34
Hi @merdiano 

This is actually a correct behaviour, because `localhost` is not a valid "full" hostname for BEAM. It would have to be something like `locahost.localdomain`. If you'd like to use `-name` and still refer to the local machine, please use `127.0.0.1` as the host name.

**Comment by merdiano** [comment] 2020-05-29 14:13
But I removed localhost from vm.args and mongooseim.cfg and used real domain.
Here is my config 
**vm.args**
## Name of the node:
##   -sname node@host
## or
##   -name node@fully.qualified.domain.name
#$
## Without @something suffix `mongooseimctl debug` uses:
##   - NODE@`hostname -s` if -sname
##   - NODE@`hostname -f` if -name
## to attach a remote shell.
-name mongooseim@my_domain.ru
## Cookie for distributed erlang
-setcookie ejabberd
## Heartbeat management; auto-restarts VM if it dies or becomes unresponsive
## (Disabled by default..use with caution!)
##-heart
+P 10000000 -env ERL_MAX_PORTS 250000
## Tweak GC to run more often
-env ERL_FULLSWEEP_AFTER 2
## With lager sasl reports are redundant so turn them off
-sasl sasl_error_logger false

**mongooseim.cfg**
%%.   ================
%%%'   SERVED HOSTNAMES
%%
%% hosts: Domains served by ejabberd.
%% You can define one or several, for example:
%% {hosts, ["example.net", "example.com", "example.org"]}.
%%
{hosts, ["my_domain.ru"] }.
%%
%% route_subdomains: Delegate subdomains to other XMPP servers.
%% For example, if this ejabberd serves example.org and you want
%% to allow communication with an XMPP server called im.example.org.
%%
%%{route_subdomains, s2s}.
%%%.   ===============
%%%'   LISTENING PORTS
%%
%% listen: The ports ejabberd will listen on, which service each is handled
%% by and what options to start it with.
%%
{listen,
 [
  %% BOSH and WS endpoints over HTTP
  { 5280, ejabberd_cowboy, [
      {num_acceptors, 10},
      {transport_options, [{max_connections, 1024}]},
      {modules, [
          {"_", "/http-bind", mod_bosh},
          {"_", "/ws-xmpp", mod_websockets, [{ejabberd_service, [
                                        {access, all},
                                        {shaper_rule, fast},
                                        {ip, {127, 0, 0, 1}},
                                        {password, "secret"}]}
          %% Uncomment to enable connection dropping or/and server-side pings
          %{timeout, 600000}, {ping_rate, 2000}
          ]}
          %% Uncomment to serve static files
          %{"_", "/static/[...]", cowboy_static,
          %  {dir, "/var/www", [{mimetypes, cow_mimetypes, all}]}
          %},
          %% Example usage of mod_revproxy
          %% {"_", "/[...]", mod_revproxy, [{timeout, 5000},
          %%                                % time limit for upstream to respond
          %%                                {body_length, 8000000},
          %%                                % maximum body size (may be infinity)
          %%                                {custom_headers, [{<<"header">>,<<"value">>}]}
          %%                                % list of extra headers that are send to upstream
          %%                               ]}
          %% Example usage of mod_cowboy
          %% {"_", "/[...]", mod_cowboy, [{http, mod_revproxy,
          %%                                [{timeout, 5000},
          %%                                 % time limit for upstream to respond
          %%                                 {body_length, 8000000},
          %%                                 % maximum body size (may be infinity)
          %%                                 % list of extra headers that are send to upstream
          %%                                ]},
          %%                               {ws, xmpp, mod_websockets}
          %%                             ]}
      ]}
  ]},
  %% BOSH and WS endpoints over HTTPS
  { 5285, ejabberd_cowboy, [
        {num_acceptors, 10},
        {transport_options, [{max_connections, 1024}]},
        {ssl, [{certfile, "priv/ssl/fake_cert.pem"}, {keyfile, "priv/ssl/fake_key.pem"}, {password, ""}]},
        {modules, [
            {"_", "/http-bind", mod_bosh},
            {"_", "/ws-xmpp", mod_websockets, [
            %% Uncomment to enable connection dropping or/and server-side pings
            %{timeout, 600000}, {ping_rate, 60000}
            ]}
            %% Uncomment to serve static files
            %{"_", "/static/[...]", cowboy_static,
            %  {dir, "/var/www", [{mimetypes, cow_mimetypes, all}]}
            %},
        ]}
    ]},
  %% MongooseIM HTTP API it's important to start it on localhost
  %% or some private interface only (not accessible from the outside)
  %% At least start it on different port which will be hidden behind firewall
  %%{ {8088, "127.0.0.1"} , ejabberd_cowboy, [
  %%    {num_acceptors, 10},
  %%    {transport_options, [{max_connections, 1024}]},
  %%    {modules, [
  %%        {"localhost", "/api", mongoose_api_admin, []}
  %%    ]}
  %%]},
  { 8089 , ejabberd_cowboy, [
      {num_acceptors, 10},
      {transport_options, [{max_connections, 1024}]},
      {protocol_options, [{compress, true}]},
      {ssl, [{certfile, "priv/ssl/fake_cert.pem"}, {keyfile, "priv/ssl/fake_key.pem"}, {password, ""}]},
      {modules, [
          {"_", "/api/sse", lasse_handler, [mongoose_client_api_sse]},
          {"_", "/api/messages/[:with]", mongoose_client_api_messages, []},
          {"_", "/api/contacts/[:jid]", mongoose_client_api_contacts, []},
          {"_", "/api/rooms/[:id]",    mongoose_client_api_rooms, []},
          {"_", "/api/rooms/[:id]/config",    mongoose_client_api_rooms_config, []},
          {"_", "/api/rooms/:id/users/[:user]",    mongoose_client_api_rooms_users, []},
          {"_", "/api/rooms/[:id]/messages",    mongoose_client_api_rooms_messages, []},
          %% Swagger
          {"_", "/api-docs", cowboy_swagger_redirect_handler, {priv_file, cowboy_swagger, "swagger/index.html"}},
          {"_", "/api-docs/swagger.json", cowboy_swagger_json_handler, #{}},
          {"_", "/api-docs/[...]", cowboy_static, {priv_dir, cowboy_swagger, "swagger", [{mimetypes, cow_mimetypes,
 all}]}}
      ]}
  ]},
  %% Following HTTP API is deprected, the new one abouve should be used instead
  { {5288, "my_domain.ru"} , ejabberd_cowboy, [
      {num_acceptors, 10},
      {transport_options, [{max_connections, 1024}]},
      {modules, [
         {"tmchat.ru", "/api", mongoose_api, [{handlers, [mongoose_api_metrics,
                                                           mongoose_api_users]}]}
      ]}
  ]},
  { 5222, ejabberd_c2s, [
                        %%
                        %% If TLS is compiled in and you installed a SSL
                        %% certificate, specify the full path to the
                        %% file and uncomment this line:
                        %%
                        {certfile, "priv/ssl/fake_server.pem"}, starttls,
                        
                        %%{zlib, 10000},
                        %% https://www.openssl.org/docs/apps/ciphers.html#CIPHER_STRINGS
                        %% {ciphers, "TLSv1.2:TLSv1.3"},
                        {access, c2s},
                        {shaper, c2s_shaper},
                        {max_stanza_size, 65536}
                        
                       ]},
  
  %%
  %% To enable the old SSL connection method on port 5223:
  %%
  %%{5223, ejabberd_c2s, [
  %%                    {access, c2s},
  %%                    {shaper, c2s_shaper},
  %%                    {certfile, "/path/to/ssl.pem"}, tls,
  %%                    {max_stanza_size, 65536}
  %%                   ]},
  { 5269, ejabberd_s2s_in, [
                           {shaper, s2s_shaper},
                           {max_stanza_size, 131072}
                           
                          ]}
  %%
  %% ejabberd_service: Interact with external components (transports, ...)
  %%
  ,{8888, ejabberd_service, [
                {access, all},
                {shaper_rule, fast},
                {ip, {127, 0, 0, 1}},
                {password, "secret"}
           ]}
  %%
  %% ejabberd_stun: Handles STUN Binding requests
  %%
  %%{ {3478, udp}, ejabberd_stun, []}
 ]}.
%%
%% s2s_use_starttls: Enable STARTTLS + Dialback for S2S connections.
%% Allowed values are: false optional required required_trusted
%% You must specify a certificate file.
%%
{s2s_use_starttls, optional}.
% s2s_certfile: Specify a certificate file.
%%
{s2s_certfile, "priv/ssl/fake_server.pem"}.
%% https://www.openssl.org/docs/apps/ciphers.html#CIPHER_STRINGS
%% {s2s_ciphers, "TLSv1.2:TLSv1.3"}.
%%
%% domain_certfile: Specify a different certificate for each served hostname.
%%
%%{domain_certfile, "example.org", "/path/to/example_org.pem"}.
%%{domain_certfile, "example.com", "/path/to/example_com.pem"}.
%%
%% S2S whitelist or blacklist
%%
%% Default s2s policy for undefined hosts.
%%
{s2s_default_policy, deny }.
%%
%% Allow or deny communication with specific servers.
%%
%%{ {s2s_host, "goodhost.org"}, allow}.
%%{ {s2s_host, "badhost.org"}, deny}.
{outgoing_s2s_port, 5269 }.
%%
%% IP addresses predefined for specific hosts to skip DNS lookups.
%% Ports defined here take precedence over outgoing_s2s_port.
%% Examples:
%%
%% { {s2s_addr, "example-host.net"}, {127,0,0,1} }.
%% { {s2s_addr, "example-host.net"}, { {127,0,0,1}, 5269 } }.
%% { {s2s_addr, "example-host.net"}, { {127,0,0,1}, 5269 } }.
%%
%% Outgoing S2S options
%%
%% Preferred address families (which to try first) and connect timeout
%% in milliseconds.
%%
%%{outgoing_s2s_options, [ipv4, ipv6], 10000}.
%%
%%%.   ==============
%%%'   SESSION BACKEND
%%{sm_backend, {mnesia, []}}.
%% Requires {redis, global, default, ..., ...} outgoing pool
%%{sm_backend, {redis, []}}.
{sm_backend, {mnesia, []} }.
%%%.   ==============
%%%'   AUTHENTICATION
%% Advertised SASL mechanisms
%%{sasl_mechanisms, [cyrsasl_scram_sha1, cyrsasl_plain]}.
...

**Comment by Neustradamus** [comment] 2020-12-31 19:51
@merdiano: Any news for your issue?

**Comment by gustawlippa** [comment] 2022-04-01 12:37
Closing, since it seems that the issue should be resolved in the newer MongooseIM version, looking at the `ejabberd_listener` changes. Please reopen if the problem is still relevant in [5.0.0](https://github.com/esl/MongooseIM/tree/5.0.0).

**Closed by gustawlippa** 2022-04-01 12:37 UTC
