### ISSUE TITLE
Chat history is not working properly.

### ISSUE THREAD

**Issue by fluttercid** [esl/MongooseIM#4269] opened 2024-04-18 14:59 UTC
MongooseIM version: 6.1.0
Installed from: Helm chart
![image](https://github.com/esl/MongooseIM/assets/65621167/460552f8-12b6-443d-aa35-1a9edd2071de)
Erlang/OTP version: N/A

Hello.
I am using bosh from web client and there are two issues now.
1. When a user re-login (refresh page), the last message is sent even mam history does have this message.
 : It causes Individual chat and group chat; it happens more often on group chat.
2. When a user sends a message on group chat, a time (using stamp on mam history) is not match
 1) case 1
    : totally wrong     
![image](https://github.com/esl/MongooseIM/assets/65621167/aa908d03-7403-49fc-b1a7-0bad01b25e2e)
 2) case 2
    : not same as sent time (6 or 7 hours behind, or just random)

[Attachment]
- mongooseim.toml (mam and muc part)
![image](https://github.com/esl/MongooseIM/assets/65621167/40cc4a52-580e-4e0f-8053-ff01957e980c)
- Server logs (there is no specific errors)
![image](https://github.com/esl/MongooseIM/assets/65621167/f4e8b453-413c-49cb-bb25-314e3d8098b9)

Could you help me to resolve these issues?
Thank you for your time.

**Comment by arcusfelis** [comment] 2024-04-30 12:29
Hi,

> When a user sends a message on group chat, a time (using stamp on mam history) is not match
What do you mean? Please, post more details (stanzas, ids and what time is and should be)

**Comment by fluttercid** [comment] 2024-05-01 11:17
Hi,
Thank you for the response.
This is data in mam_muc_message
![image](https://github.com/esl/MongooseIM/assets/65621167/2f23c84b-1c21-4ecb-98a0-b4de4f66afbe)
and this is stanza from response of MAM
![image](https://github.com/esl/MongooseIM/assets/65621167/c548017b-ac26-4428-9512-bdb6d1d9f6a6)
I tested it around 3 weeks ago and it shouldn't be 1970.
If there is anything I need to add, please let me know.
Thank you.

**Comment by arcusfelis** [comment] 2024-05-01 13:27
yes, looks like somehow we ended up encoding timestamp as 0.
Could be a bug in `mod_mam_utils:generate_message_id(TS)` (TS is provided 0). It gets it from `Activity#activity.message_time` in mod_muc_room.

Do you use mod_muc or mod_muc_light by the way?

**Comment by fluttercid** [comment] 2024-05-02 11:48
I am using a mod_muc now.

**Comment by arcusfelis** [comment] 2024-05-15 14:01
`same_mam_id_for_peers=true`  could be a reason.

**Comment by fluttercid** [comment] 2024-05-17 14:37
Oh, I will change and test it.
Thank you.

**Comment by arcusfelis** [comment] 2024-06-03 16:23
Hi, I've tried to reproduce it, and unable to. So, maybe more info would help. Do you send message using XMPP API or graphql?

**Comment by arcusfelis** [comment] 2024-06-03 19:22
If you can easily reproduce ARCHIVING error, you can try to trace the error.
1. Open mongooseim shell (i.e. `mongooseim debug`).
2. Enable tracing and wait to check what you got:

```
recon_trace:calls({mongoose_hooks, filter_room_packet, return_trace}, 1000, [{scope, global}]).
```

Just wanna confirm `timestamp = 0` would be in traced logs.

**Comment by arcusfelis** [comment] 2024-06-03 20:03
OK, I actually traced it.

```
when=2024-06-03T19:52:43.956382+00:00 level=error what=filter_room_packet pid=<0.7249.0> at=mod_muc_room:broadcast_room_packet/5:909 event_data_from_nick=unique_carol_unnamed_171_same_stanza_id_for_muc_172_nickname event_data_room_jid="{jid,<<\"room-ac8811f7ab\">>,<<\"muc.localhost\">>,<<>>}" event_data_affiliation=owner event_data_role=moderator event_data_from_jid="{jid,<<\"carol_unnamed_171_same_stanza_id_for_muc_172\">>,<<\"localhost\">>,<<\"res1\">>}" event_data_timestamp=0 packet="{xmlel,<<\"message\">>,[{<<\"type\">>,<<\"groupchat\">>},{<<\"to\">>,<<\"room-ac8811f7ab@muc.localhost\">>}],[{xmlel,<<\"body\">>,[],[{xmlcdata,<<\"Hi!\">>}]}]}"
```

So, filter_room_packet is called with timestamp=0 (i.e. event_data_timestamp=0 in the logs).


after that we call:

```
generate_message_id(CandidateStamp) ->
    NodeNum = mongoose_node_num:node_num(),
    UniqueStamp = mongoose_mam_id:next_unique(CandidateStamp),
```

i.e. `generate_message_id(0). mongoose_mam_id:next_unique(0).`.

If node just started we get:

```
mod_mam_utils:generate_message_id(0).
257
```

But if node was already working and processed some regular messages we get the bug hiding itself (or fixing itself):

```
mod_mam_utils:generate_message_id(erlang:system_time(microsecond)).
439665894343957761
(mongooseim@localhost)3> mod_mam_utils:generate_message_id(0).
439665894343958017
```

Fix would be probably to set timestamp to `erlang:system_time(microsecond)` in MUC activity logic (which is some old weird code).

**Comment by arcusfelis** [comment] 2024-06-03 20:05
As side effects, you can also get timestamps for MUC messages set to the timestamp of the last sent private message (i.e. 8 hours in the past or just random).

Also, funny numbering:

```
mod_mam_utils:generate_message_id(0).
257
(mongooseim@localhost)2> mod_mam_utils:generate_message_id(0).
513
(mongooseim@localhost)3> mod_mam_utils:generate_message_id(0).
769
(mongooseim@localhost)4> mod_mam_utils:generate_message_id(0).
1025
```

**Comment by arcusfelis** [comment] 2024-06-06 10:17
Hi, the fix has been merged into the master branch.

**Comment by fluttercid** [comment] 2024-06-07 11:16
Thank you so much for fixing it.
I will pull 6.1 version image and test it.

**Closed** 2024-09-13 15:47 UTC
