### ISSUE TITLE
Server performance issue with 50k chats in muc_light+ mysql

### ISSUE THREAD

**Issue by deadjdona** [esl/MongooseIM#1561] opened 2017-11-08 21:01 UTC
MongooseIM version: 2.1.0
Installed from: source
Erlang/OTP version: 20

Config: mam enabled for muc_light, mysql for mam (amazon aurora), redis for sessions.
User have 50k chats with 1-2 incoming messages in each.

Problem:
when user make clear login (without caches on client side) and try to get full rooms list, server is heavily loaded.

Actually client receive 1st page of chats list, request next page, and server start to send 1000's requests per second to database, and this continue for 30 seconds, then client receive next page from chat list, and everything repeats.

I've tried to increase page size from 100 to 1000 chats, and same stuff happens.
Each page sent with 30 sec delay, and 1500 requests _per second_ to database all this time.
Haven't tried to set page to 50k though.

Here's request for chats list next page, for first page same request without "after":
`<iq type="get" to="muclight.xmpp.domain.com" id="EF159161-A311-112A-A11F-DCC89011E64F"><query xmlns="http://jabber.org/protocol/disco#items"><set xmlns="http://jabber.org/protocol/rsm"><after>45fccbae7386868b436381a4@muclight.xmpp.domain.com</after></set></query></iq>`

**Comment by fenek** [comment] 2017-11-09 09:34
Hi @deadjdona 

Thanks for the bug report. The behaviour is indeed strange, because getting a list of user rooms currently involves single SQL query. I'm not sure where these thousands/sec. come from. I'll try to reproduce it in near future.

However, there is room for improvement of this function efficiency for sure, like applying RSM in DB layer, not MUC Light one.

**Comment by deadjdona** [comment] 2017-11-09 13:28
@fenek yeah, really weird.
can you provide some code snippets for me to debug? 
i can launch mongooseim live and check (but i do not know _what_ to check =)

**Comment by fenek** [comment] 2017-11-09 14:00
Please enable general log in MySQL in order to check precisely what queries are executed when a list of rooms is fetched.

**Comment by deadjdona** [comment] 2017-11-09 15:05
That's amazon aurora, is this.possible?

**Comment by fenek** [comment] 2017-11-22 16:29
Hi @deadjdona 

I'm sorry, I was too occupied to reply over last two weeks. :(

You may try to setup a debug to learn what and how many queries are executed in order to retrieve user's room list (in MongooseIM console; please use `attach`, not `debug`!)

```
dbg:tracer().
dbg:p(all, c).
dbg:tp(mongoose_rdbms, sql_query, x).
```

After you enable this, fetch a room list once and see how many calls are logged to the console. You will also see not only the call but also the return, so you may roughly assess how much time it took to complete the query.

**Comment by deadjdona** [comment] 2017-11-24 16:49
1000's of queries like this:

```
(<0.11974.0>) call mongoose_rdbms:sql_query(<<"xmpp.domain.com">>,["SELECT version, opt, val",
 " FROM muc_light_rooms AS r LEFT OUTER JOIN muc_light_config AS c ON r.id = c.room_id WHERE r.luser = '",
 <<"dd378f40269099cabcb1ca6829">>,"' AND r.lserver = '",
 <<"muclight.xmpp.domain.com">>,"'"])
(<0.11974.0>) returned from mongoose_rdbms:sql_query/2 -> {selected,
                                                           [{<<"1510-153953-881828">>,
                                                             <<"key">>,
                                                             <<>>},
                                                            {<<"1510-153953-881828">>,
                                                             <<"device">>,
                                                             <<>>},
                                                            {<<"1510-153953-881828">>,
                                                             <<"photourl">>,
                                                             <<>>},
                                                            {<<"1510-153953-881828">>,
                                                             <<"roomname">>,
                                                             <<>>},
                                                            {<<"1510-153953-881828">>,
                                                             <<"secure">>,<<>>},
                                                            {<<"1510-153953-881828">>,
                                                             <<"readOnly">>,
                                                             <<"0">>}]}

```

**Comment by fenek** [comment] 2017-11-27 14:50
Are you 100% sure these thousands of queries are triggered by only one user requesting one page of results?

**Comment by deadjdona** [comment] 2017-11-29 21:25
yep, one user login into account with 40k chats.
immediately i see this queries and load increase on MIM and SQL.
i've tried chat list page size 100 and 1000 - same effect.
we have some custom properties added to each chat, not sure if this is the case.

**Comment by fenek** [comment] 2019-05-29 13:31
Applies to pretty old MongooseIM version and hasn't been reported since then. Closing.

**Closed by fenek** 2019-05-29 13:31 UTC
Labels: community
