### ISSUE TITLE
One instance of MongooseIM can not support more than 65k simultaneously users

### ISSUE THREAD

**Issue by emnvn** [esl/MongooseIM#1077] opened 2016-11-17 07:35 UTC
MongooseIM version: 2.0.0beta
Installed from: source
Erlang/OTP version: 17.5

I have loaded test a MongooseIM server with these information:

1. Server MongooseIM
OS: RHEL 6 64 bit
CPU: 8 core
RAM: 32 GB

2. Mongoose Erlang VM config
+K true
+A 8
env ERL_FULLSWEEP_AFTER 8
 ERL_MAX_PORT: 300000
+P 600000
File Open Limit: 131072

3. Tsung test scenario
Session duration: 1000  seconds
Arrival Rate: 200 user/seconds
Roster Size: 100

Flow:  connect -> Think(1) -> auth_sasl -> think (1)-> connect -> auth_sasl_bind-> auth_sasl_session -> think (1)-> iq:roster:get -> think (1)-> presence:broadcast -> think (120) -> close

The result that I can only see about 65000 online user, I have see the current status when online user is about 65000

length(erlang:ports()) ~ 65000
length(erlang:processes()) ~120000
Peak CPU: 70%
Peak RAM: 7GB
File limit open (cat /proc/sys/fs/file-nr) is about 65K

I tried to increase simultaneously  users to 100k but there is no way (I added new tsung client on another PC to bypass 65k tcp port/PC ). Is there 65k users is the limit for one MongooseIM instance ?

Thanks for your help.

**Comment by michalwski** [comment] 2016-11-17 08:29
Hi @emnvn 

Thank you for contacting us. It looks like it's an issue on the load generator side. From single network interface you are able to open around 65K connections. If you want to go beyond, you need to have more network interfaces on the same machine (they can be virtual interfaces) or use more machines to generate the load.

Also you can have a look at our load testing tool https://github.com/esl/amoc. You can write scenarios in Erlang so basically you can do anything you want from the scenario.

**Comment by emnvn** [comment] 2016-11-17 14:39
Hi @michalwski,

Thanks for your response. I also thought about the problem of network interface (maximum 65k ports), I added a new tsung client on another PC, so I have two tsung clients on two separate machines but the load is not increased to more than 65k users on MongooseIM server.

I tried to increase limits that I known (Process, Max port on Erlang VM, max open file description on OS but It can not solve my problem. I don't see any error on MongooseIM log.

Beside that with my server resource, can you estimate that how many concurrent  online users that  One Mongoose IM instance can serve well?

I will take time to try your load test tool (amoc).

Thanks you very much,
Have a nice day!
Nghia Em

**Comment by michalwski** [comment] 2016-11-17 15:08
I see that I missed important peace of information from your issue:

> File limit open (cat /proc/sys/fs/file-nr) is about 65K

This is your root cause right now. Every opened connection is represented as a file descriptor. In order to handle more than 65K connection you need to increase this limit. 

>Beside that with my server resource, can you estimate that how many concurrent online users that One Mongoose IM instance can serve well?

You should be able to connect 300-400k users without any problems on such a machine.

**Comment by emnvn** [comment] 2016-11-17 15:19
Hi @michalwski ,

I don't describe clearly:
cat /proc/sys/fs/file-nr
65432     0       131072

It mean that ~65K/131K file is opened, there are very many available file to open.

Thanks for your estimate value. I really love it :)
Best Regards,
Nghia Em

**Comment by michalwski** [comment] 2016-11-17 16:09
With this settings you should definitely be able to fit around 130K users (because of the file limit).

At this moment I don't have any other ideas. If this was a server issue you would most probably see some errors in logs. I suggest double checking `ejabberd.log` and `crash.log`. Also maybe you will find some errors in tsung logs.

**Comment by emnvn** [comment] 2016-11-17 16:13
Yes, Thanks you very much. I  will try to detect the problem, When I resolve it I will tell you.

Thanks for your help,
Have a nice day!

**Comment by michalwski** [comment] 2017-01-24 08:54
I'm closing this issue as it get too old. Please re-open it if you have further questions or updates.

**Closed by michalwski** 2017-01-24 08:54 UTC
