### ISSUE TITLE
Cowboy with own CA

### ISSUE THREAD

**Issue by ctjhai** [esl/MongooseIM#1341] opened 2017-06-13 09:02 UTC
MongooseIM version: 2.0.1
Installed from: https://packages.erlang-solutions.com/erlang/mongooseim/FLAVOUR_1_main/mongooseim_2.0.1-1~ubuntu~xenial_amd64.deb
Erlang/OTP version: Erlang/OTP 18 [erts-7.3.1] [source-25741fd]

I'm adding a TLS certificate for Cowboy, in particular for client REST API, i.e. port 8089. The snippet of configuration on `ejabberd` is shown below:
```
{ 8089 , ejabberd_cowboy, [
      {num_acceptors, 10},
      {max_connections, 1024},
      {compress, true},
      {ssl, [
            {certfile, "priv/ssl/my.cert.pem"},
            {keyfile, "priv/ssl/my.key.pem"},
            {cacertfile, "priv/ssl/ca.cert.pem"}
            ]},
      %%{ssl, [{certfile, "priv/ssl/fake_cert.pem"}, {keyfile, "priv/ssl/fake_key.pem"}, {password, ""}]},
      {modules, [
          {"_", "/api/sse", lasse_handler, [mongoose_client_api_sse]},
          {"_", "/api/messages/[:with]", mongoose_client_api_messages, []},
          {"_", "/api/rooms/[:id]",    mongoose_client_api_rooms, []},
          {"_", "/api/rooms/:id/users/[:user]",    mongoose_client_api_rooms_users, []},
          {"_", "/api/rooms/[:id]/messages",    mongoose_client_api_rooms_messages, []}
      ]}
  ]},
```
The catch is that I use my own CA (`ca.cert.pem`), which signs my certificate (`my.cert.pem`). I run into a problem and here are the diagnostics:

- Testing using OpenSSL on client side returns "insufficient security error".
```
$ openssl s_client -tls1_2 -status -debug -connect {SERVER_NAME}:8089
... [truncated on purpose] ...
40735107788800:error:1409442F:SSL routines:ssl3_read_bytes:tlsv1 alert insufficient security:ssl/record/rec_layer_s3.c:1469:SSL alert number 71
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 133 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1497343084
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```
- Replace the cert using a self-signed certificate, OpenSSL can connect perfectly. With self-signed certificate, the following configuration is used:
```
      {ssl, [
            {certfile, "priv/ssl/my-self-signed.cert.pem"},
            {keyfile, "priv/ssl/my.key.pem"},
            ]},
```
- Then I tried to concatenate my certificate and the CA certificate onto a PEM file, but I ran into the same error (insufficient security). The configuration I used is below:
```
      {ssl, [
            {certfile, "priv/ssl/cert-and-cacert.pem"},
            {keyfile, "priv/ssl/my.key.pem"},
            ]},
```
- By the way, the old style TLS (`p1_tls`), which is configured for `ejabberd_c2s` port 5222 and 5223 using a concatenation of certificate and private key, works perfectly. It even works even without appending my CA certificate.

How should the configuration be if I want to use my own CA for Cowboy?

Cheers,
CJ

**Comment by fenek** [comment] 2017-06-13 10:29
Hi @ctjhai 

Setting `certfile` and `keyfile` is enough, since the client should have its own CA certificate copy and verify server's certificate with it.

It's my guess but maybe if the server is offering CA certificate as well, OpenSSL tries to check the CA certificate against known CAs in the OS and rejects it?

**Comment by rslota** [comment] 2017-06-13 11:19
Hi @ctjhai 

(just a guess but maybe also worth trying)

It looks like your "real" certificate is assigned to a hostname. If the SNI is enabled on server, you cannot connect without specifying this hostname via `-servername {HOSTNAME}` option for `openssl` client. 

Also, note that with this configuration you have no CA check on your client. You need to add you CA cert to `openssl` client or you system CA bundle. TLS clients treat CA certificates sent by server (`cacertfile`) only as "intermediate" CA certificates. There still need to be the "top-level" CA in your system bundle and/or in CA file supplied to `openssl` via `-CAfile` option.

**Comment by ctjhai** [comment] 2017-06-13 11:43
Hi @fenek @rslota,

Many thanks for your response. I don't think we are at the stage of certificate verification stage yet. The full output log is shown below:
```
$> openssl s_client -CAfile ca-cert.pem -tls1_2 -msg -status -debug -connect {SERVER_NAME}:8089
CONNECTED(00000003)
>>> ??? [length 0005]
    16 03 01 00 b4
>>> TLS 1.2, Handshake [length 00b4], ClientHello
    01 00 00 b0 03 03 38 f9 d2 6a 79 92 90 3c b8 b8
    52 1e ad 28 04 11 6d 5b 4d a3 53 15 c9 cb 16 62
    82 78 3b f4 f4 32 00 00 38 c0 2c c0 30 00 9f cc
    a9 cc a8 cc aa c0 2b c0 2f 00 9e c0 24 c0 28 00
    6b c0 23 c0 27 00 67 c0 0a c0 14 00 39 c0 09 c0
    13 00 33 00 9d 00 9c 00 3d 00 3c 00 35 00 2f 00
    ff 01 00 00 4f 00 0b 00 04 03 00 01 02 00 0a 00
    0a 00 08 00 1d 00 17 00 19 00 18 00 23 00 00 00
    0d 00 20 00 1e 04 03 05 03 06 03 08 04 08 05 08
    06 04 01 05 01 06 01 02 03 02 01 02 02 04 02 05
    02 06 02 00 05 00 05 01 00 00 00 00 00 16 00 00
    00 17 00 00
write to 0x7fa608600000 [0x7fa60900fa00] (185 bytes => 185 (0xB9))
0000 - 16 03 01 00 b4 01 00 00-b0 03 03 38 f9 d2 6a 79   ...........8..jy
0010 - 92 90 3c b8 b8 52 1e ad-28 04 11 6d 5b 4d a3 53   ..<..R..(..m[M.S
0020 - 15 c9 cb 16 62 82 78 3b-f4 f4 32 00 00 38 c0 2c   ....b.x;..2..8.,
0030 - c0 30 00 9f cc a9 cc a8-cc aa c0 2b c0 2f 00 9e   .0.........+./..
0040 - c0 24 c0 28 00 6b c0 23-c0 27 00 67 c0 0a c0 14   .$.(.k.#.'.g....
0050 - 00 39 c0 09 c0 13 00 33-00 9d 00 9c 00 3d 00 3c   .9.....3.....=.<
0060 - 00 35 00 2f 00 ff 01 00-00 4f 00 0b 00 04 03 00   .5./.....O......
0070 - 01 02 00 0a 00 0a 00 08-00 1d 00 17 00 19 00 18   ................
0080 - 00 23 00 00 00 0d 00 20-00 1e 04 03 05 03 06 03   .#..... ........
0090 - 08 04 08 05 08 06 04 01-05 01 06 01 02 03 02 01   ................
00a0 - 02 02 04 02 05 02 06 02-00 05 00 05 01 00 00 00   ................
00b0 - 00 00 16 00 00 00 17                              .......
00b9 - <SPACES/NULS>
read from 0x7fa608600000 [0x7fa609006603] (5 bytes => 5 (0x5))
0000 - 15 03 03 00 02                                    .....
<<< ??? [length 0005]
    15 03 03 00 02
read from 0x7fa608600000 [0x7fa609006608] (2 bytes => 2 (0x2))
0000 - 02 47                                             .G
<<< TLS 1.2, Alert [length 0002], fatal insufficient_security
    02 47
140735107788800:error:1409442F:SSL routines:ssl3_read_bytes:tlsv1 alert insufficient security:ssl/record/rec_layer_s3.c:1469:SSL alert number 71
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 185 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1497353772
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```

As you can see above, I included `-CAfile` param in my OpenSSL call. Furthermore, I don't use SNI on my server. 

Looking at RFC5246 (TLS), we have
```
   insufficient_security
      Returned instead of handshake_failure when a negotiation has
      failed specifically because the server requires ciphers more
      secure than those supported by the client.  This message is always
      fatal.
```
How can this change the cipher on the server side where a self-signed certificate works?

CJ

**Comment by fenek** [comment] 2017-06-13 11:52
I've google some information suggesting that there was a bug in Erlang's SSL implementation, which caused it to return `insufficient_security` error improperly. It could be observed in e.g OTP 18.3.3. Is it the version you're using? If so, can you please try e.g. 18.3.4 or 19.0?

**Comment by ctjhai** [comment] 2017-06-13 11:55
Hi @fenek 

Thanks for your fast response. I'm using MongooseIM downloaded from https://packages.erlang-solutions.com/erlang/mongooseim/FLAVOUR_1_main/mongooseim_2.0.1-1~ubuntu~xenial_amd64.deb, which I believe is shipped with a version of Erlang OTP, i.e. `Erlang/OTP version: Erlang/OTP 18 [erts-7.3.1] [source-25741fd]`.

How can I change to a different version of Erlang OTP in this case?

CJ

**Comment by fenek** [comment] 2017-06-13 14:23
I'm not sure actually if it's a matter of OTP version, because I hasn't been able to reproduce it locally. Can you please use Wireshark or similar tool that can decode TLS client hello and check what cipher suites are advertised by the client at the beginning of the handshake? It will be definitely faster than trying to decode the packet you've pasted. :)

As an alternative, you could try installing OTP 19.x from ESL packages and compile MongooseIM from source and see if it helps.

**Comment by ctjhai** [comment] 2017-06-13 14:57
HI @fenek,

I made sure my OpenSSL to send a specific TLSv1.2 cipher suite (TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) and from Wireshark I have the following cipher suites sent:
```
Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)
Cipher Suite: TLS_EMPTY_RENEGOTIATION_INFO_SCSV (0x00ff)
```
Not sure if I can disable sending SCSV flag via OpenSSL though, but I'm not sure if the error is caused by this. What do you think?

I have not got time on reinstalling OTP 19.x, but report back once I've tried this.

**Comment by fenek** [comment] 2017-06-16 14:35
It could be the case as well, that when CA cert if provided, server expects client certificate signed by this certificate. It may be characteristic to this OTP version. I guess inspecting OTP source code would explain what's going on. :)

**Comment by fenek** [comment] 2017-07-05 08:56
Hi @ctjhai 

Is this issue still valid? Have you managed to resolve it perhaps?

**Comment by ctjhai** [comment] 2017-07-05 09:04
@fenek I should be able to tell you in a week or so, will be rebuilding a version using Erlang 19. Will keep you updated.

**Comment by fenek** [comment] 2018-03-20 16:02
Please reopen if the issue is still valid.

**Closed by fenek** 2018-03-20 16:02 UTC
