### ISSUE TITLE
Crash with Riak Backend

### ISSUE THREAD

**Issue by alirizakeles** [esl/MongooseIM#597] opened 2015-11-28 08:47 UTC
I have installed prebuild package for ubuntu into my ubuntu 14.04.03 box. At the same box I have installed riak 2.1.1 with search option on. I executed the riak setup script which you provide and it created search indexes and bucket types successfully. 

MongooseIM started and worked properly before I configured riak backend. I tried to add users and I attached debug console etc. 

With riak backend it did not start. I only changed riak backend and hostname configuration in /usr/lib/mongooseim/etc/ejabberd.cfg. 

I tried to start it via service tool or mongooseimctl. I got same. Here is the output:

```bash
# mongooseimctl live
```
```
Exec: /usr/lib/mongooseim/erts-6.4.1/bin/erlexec -boot /usr/lib/mongooseim/releases//mongooseim -embedded -config /usr/lib/mongooseim/etc/app.config -args_file /usr/lib/mongooseim/etc/vm.args -- console
Root: /usr/lib/mongooseim
Erlang/OTP 17 [erts-6.4.1] [source-381fb6c] [64-bit] [smp:2:2] [async-threads:5] [hipe] [kernel-poll:true]

2015-11-27 22:54:32.444 [info] <0.7.0> Application lager started on node mongooseim@localhost
2015-11-27 22:54:32.476 [info] <0.87.0>@exometer_report:do_start_reporters:614 Starting reporters with []
2015-11-27 22:54:32.476 [info] <0.7.0> Application exometer started on node mongooseim@localhost
2015-11-27 22:54:32.476 [info] <0.7.0> Application bear started on node mongooseim@localhost
2015-11-27 22:54:32.491 [info] <0.7.0> Application folsom started on node mongooseim@localhost
2015-11-27 22:54:32.525 [info] <0.7.0> Application inets started on node mongooseim@localhost
2015-11-27 22:54:32.702 [info] <0.7.0> Application mnesia started on node mongooseim@localhost
2015-11-27 22:54:32.726 [info] <0.7.0> Application p1_stringprep started on node mongooseim@localhost
2015-11-27 22:54:32.768 [info] <0.7.0> Application sasl started on node mongooseim@localhost
2015-11-27 22:54:32.768 [info] <0.7.0> Application asn1 started on node mongooseim@localhost
2015-11-27 22:54:32.769 [info] <0.7.0> Application public_key started on node mongooseim@localhost
2015-11-27 22:54:32.804 [notice] <0.65.0>@lager_file_backend:128 Changed loglevel of log/ejabberd.log to info
2015-11-27 22:54:33.569 [notice] <0.65.0>@lager_file_backend:128 Changed loglevel of log/ejabberd.log to warning
2015-11-27 22:54:33.711 [error] <0.389.0> Supervisor cuesport_riak_pool_sup had child 1 started with cuesport:start_worker(1, riak_pool, {mongoose_riak,start_worker,["127.0.0.1",8087,[auto_reconnect,keepalive]]}) at undefined exit with reason {'EXIT',{undef,[{riakc_pb_socket,start_link,["127.0.0.1",8087,[auto_reconnect,keepalive]],[]},{cuesport,start_worker,3,[{file,"src/cuesport.erl"},{line,85}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,314}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,297}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,263}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,306}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}} in context start_error
2015-11-27 22:54:33.713 [error] <0.388.0> Supervisor mongoose_riak_sup had child riak_pool started with cuesport:start_link(riak_pool, 20, [mongoose_riak,riakc_pb_socket], {mongoose_riak,start_worker}, {for_all,["127.0.0.1",8087,[auto_reconnect,keepalive]]}) at undefined exit with reason {shutdown,{failed_to_start_child,1,{'EXIT',{undef,[{riakc_pb_socket,start_link,["127.0.0.1",8087,[auto_reconnect,keepalive]],[]},{cuesport,start_worker,3,[{file,"src/cuesport.erl"},{line,85}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,314}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,297}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,263}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,306}]},{proc_lib,init_p_do_apply,3,[{file,"proc_l..."},...]}]}}}} in context start_error
2015-11-27 22:54:33.726 [error] <0.211.0> CRASH REPORT Process <0.211.0> with 0 neighbours exited with reason: no match of right hand value {error,{{shutdown,{failed_to_start_child,riak_pool,{shutdown,{failed_to_start_child,1,{'EXIT',{undef,[{riakc_pb_socket,start_link,["127.0.0.1",8087,[auto_reconnect,keepalive]],[]},{cuesport,start_worker,3,[{file,"src/cuesport.erl"},{line,85}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,314}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,297}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,263}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,...}]},...]}}}}}},...}} in mongoose_riak_sup:start/4 line 39 in application_master:init/4 line 133
{"Kernel pid terminated",application_controller,"{application_start_failure,ejabberd,{bad_return,{{ejabberd_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{{shutdown,{failed_to_start_child,riak_pool,{shutdown,{failed_to_start_child,1,{'EXIT',{undef,[{riakc_pb_socket,start_link,[\"127.0.0.1\",8087,[auto_reconnect,keepalive]],[]},{cuesport,start_worker,3,[{file,\"src/cuesport.erl\"},{line,85}]},{supervisor,do_start_child,2,[{file,\"supervisor.erl\"},{line,314}]},{supervisor,start_children,3,[{file,\"supervisor.erl\"},{line,297}]},{supervisor,init_children,2,[{file,\"supervisor.erl\"},{line,263}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,306}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,237}]}]}}}}}},{child,undefined,mongoose_riak_sup,{mongoose_riak_sup,start_link,[20,\"127.0.0.1\",8087,[auto_reconnect,keepalive]]},transient,infinity,supervisor,[mongoose_riak_sup]}}}},[{mongoose_riak_sup,start,4,[{file,\"src/mongoose_riak_sup.erl\"},{line,39}]},{ejabberd_app,start,2,[{file,\"src/ejabberd_app.erl\"},{line,62}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,272}]}]}}}}}"}

Crash dump was written to: erl_crash.dump
Kernel pid terminated (application_controller) ({application_start_failure,ejabberd,{bad_return,{{ejabberd_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{{shutdown,{failed_to_start_child,riak_poo
```

**Comment by michalwski** [comment] 2015-11-28 20:17
Did you run `make configure with-riak` before producing the release? The error you are seeing says that the riak client is undef which basically means that it was not included in the release you built.

**Comment by michalwski** [comment] 2015-11-30 10:34
Did it help?

**Comment by michalwski** [comment] 2015-11-30 12:39
One thing to clarify. Did you install MongooseIM from pre-installed package or Erlang/OTP?

**Comment by alirizakeles** [comment] 2015-11-30 13:16
> I have installed prebuild package for ubuntu into my ubuntu 14.04.03 box. At the same box I have 

Yes @michalwski, I installed prebuilt package for ubuntu which is mentioned here:
https://github.com/esl/MongooseIM#download-packages

Is that the problem?

Thanks.

**Comment by michalwski** [comment] 2015-11-30 13:19
As long as you downloaded 1.6.0 it should work. We are double checking the package. Thanks for your report.

**Comment by dexsda** [comment] 2015-12-01 09:52
I've looked into this issue; it was a problem on the package building end; the package builder failed to contain the relatively new addition of riak backends.

I've rebuilt most of the packages, including the trusty versions. They now contain the 'riak*' subdirectories in lib/ after installation, and they're up on the site. Please report if the problem is fixed once you install the updated versions.

**Comment by michalwski** [comment] 2015-12-03 08:22
@alirizakeles did you have a chance to try the rebuilt packages?

**Comment by alirizakeles** [comment] 2015-12-03 09:43
@michalwski unfortunately, i have not yet. i will inform you asap. thanks.

**Comment by michalwski** [comment] 2015-12-15 10:29
There is package for version 1.6.1 also https://www.erlang-solutions.com/resources/download.html where we added more Riak backends and fixed some minor bugs.

**Comment by michalwski** [comment] 2015-12-17 09:06
I'm closing this issue. Please re-open it if you still have troubles using Riak.

**Closed by michalwski** 2015-12-17 09:06 UTC
