### ISSUE TITLE
"Problem starting the module mod_jingle_sip"

### ISSUE THREAD

**Issue by streaps** [esl/MongooseIM#1946] opened 2018-06-24 18:29 UTC
MongooseIM version: 3.0.0
Installed from: mongooseim_3.0.0-1\~debian\~stretch_amd64.deb
Erlang/OTP version: Erlang/OTP 19

I've installed MongooseIM to test the SIP/Jingle Proxy, but it doesn't load. I have no idea if it is configuration error or a bug.

```
2018-06-24 18:04:25.759 [info] <0.31.0> Application mnesia started on node mongooseim@localhost
2018-06-24 18:04:26.372 [critical] <0.372.0>@gen_mod:start_module_for_host:150 Problem starting the module mod_jingle_sip for host <<"localhost">>
 options: []
 exit: {noproc,{gen_server,call,
                           [nkservice_all_srvs_sup,
                            {terminate_child,bk2kkvw},
                            infinity]}}
[{gen_server,call,3,[{file,"gen_server.erl"},{line,212}]},
 {nkservice_srv_sup,stop_service,1,
                    [{file,"/home/vagrant/2018-05-23_15-33-44/scripts/mongooseim/deb/mongooseim/_build/default/lib/nkservice/src/nkservice_srv_sup.erl"},
                     {line,65}]},
 {nkservice,start,2,
            [{file,"/home/vagrant/2018-05-23_15-33-44/scripts/mongooseim/deb/mongooseim/_build/default/lib/nkservice/src/nkservice.erl"},
             {line,148}]},
 {mod_jingle_sip,start,2,
                 [{file,"/home/vagrant/2018-05-23_15-33-44/scripts/mongooseim/deb/mongooseim/_build/prod/lib/mongooseim/src/jingle_sip/mod_jingle_sip.erl"},
                  {line,58}]},
 {gen_mod,start_module_for_host,3,
          [{file,"/home/vagrant/2018-05-23_15-33-44/scripts/mongooseim/deb/mongooseim/_build/prod/lib/mongooseim/src/gen_mod.erl"},
           {line,123}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
 {ejabberd_app,start,2,
               [{file,"/home/vagrant/2018-05-23_15-33-44/scripts/mongooseim/deb/mongooseim/_build/prod/lib/mongooseim/src/ejabberd_app.erl"},
                {line,72}]},
 {application_master,start_it_old,4,
                     [{file,"application_master.erl"},{line,273}]}]
2018-06-24 18:04:26.374 [critical] <0.372.0>@gen_mod:start_module_for_host:155 mongooseim initialization was aborted because a module start failed.
The trace is [{gen_server,call,3,[{file,"gen_server.erl"},{line,212}]},{nkservice_srv_sup,stop_service,1,[{file,"/home/vagrant/2018-05-23_15-33-44/scripts/mongooseim/deb/mongooseim/_build/default/lib/nkservice/src/nkservice_srv_sup.erl"},{line,65}]},{nkservice,start,2,[{file,"/home/vagrant/2018-05-23_15-33-44/scripts/mongooseim/deb/mongooseim/_build/default/lib/nkservice/src/nkservice.erl"},{line,148}]},{mod_jingle_sip,start,2,[{file,"/home/vagrant/2018-05-23_15-33-44/scripts/mongooseim/deb/mongooseim/_build/prod/lib/mongooseim/src/jingle_sip/mod_jingle_sip.erl"},{line,58}]},{gen_mod,start_module_for_host,3,[{file,"/home/vagrant/2018-05-23_15-33-44/scripts/mongooseim/deb/mongooseim/_build/prod/lib/mongooseim/src/gen_mod.erl"},{line,123}]},{lists,foreach,2,[{file,"lists.erl"},{line,1338}]},{ejabberd_app,start,2,[{file,"/home/vagrant/2018-05-23_15-33-44/scripts/mongooseim/deb/mongooseim/_build/prod/lib/mongooseim/src/ejabberd_app.erl"},{line,72}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,273}]}].
```

**Comment by michalwski** [comment] 2018-06-25 13:15
Hi @streaps,

Thanks for trying our Jingle/SIP integration.
Are you able to compile the MongooseIM from source? Looks like there is an issue with our deb package and `mod_jingle_sip`.

If you try, please first run `./tools/configure with-all` to be sure that all required dependencies are included in the release.
After the configure script, please run `make rel` this will build the release in `_build/rel/prod`.

**Comment by streaps** [comment] 2018-06-25 13:42
I never tried to build any Erlang code before. I'm not sure how successful that would be, but I could try.

**Comment by michalwski** [comment] 2018-06-25 13:50
I you are familiar with docker, you can try our docker image available here: https://hub.docker.com/r/mongooseim/mongooseim/ there are instructions how to provide your custom config file.

**Comment by streaps** [comment] 2018-06-25 15:58
Thanks Michał,

unfortunately Docker is not an option. I'm running everything in LXC containers and Docker inside LXC seems to be unsupported.

**Comment by streaps** [comment] 2018-06-25 16:13
I just tried 3.0.0 and 2.2.2 on Ubtunu 16.04, same problem.

**Comment by streaps** [comment] 2018-06-26 11:44
I also installed MongooseIM 3.0.0 package on Centos 7 (LXC container). Fresh install, config files untouched. It crashes on startup with some error about nksip: 
```
[root@mongooseim-03 mongooseim]# mongooseimctl foreground                                                                         
Root: //usr/lib/mongooseim
Exec: //usr/lib/mongooseim/erts-7.3/bin/erlexec -noshell -noinput +Bd -boot //usr/lib/mongooseim/releases/3.0.0/mongooseim -embedded -config //etc/mongooseim/app.config -args_file //etc/mongooseim/vm.args -args_file //etc/mongooseim/vm.dist.args -- foreground

=INFO REPORT==== 26-Jun-2018::11:34:36 ===
    msg: "Starting reporters with []\n"
    options: []
2018-06-26 11:34:36.332 [info] <0.7.0> Application lager started on node mongooseim@localhost
2018-06-26 11:34:36.332 [info] <0.7.0> Application cowlib started on node mongooseim@localhost
2018-06-26 11:34:36.335 [info] <0.7.0> Application cowboy started on node mongooseim@localhost
2018-06-26 11:34:36.342 [notice] <0.272.0>@lager_file_backend:131 Changed loglevel of /var/log/mongooseim/ejabberd.log to info
2018-06-26 11:34:36.390 [info] <0.7.0> Application mnesia exited with reason: stopped
2018-06-26 11:34:36.405 [info] <0.7.0> Application mnesia started on node mongooseim@localhost
2018-06-26 11:34:36.791 [notice] <0.272.0>@lager_file_backend:131 Changed loglevel of /var/log/mongooseim/ejabberd.log to warning
{"Kernel pid terminated",application_controller,"{application_start_failure,nksip,{bad_return,{{nksip_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,enoent}},[{nklib_config,make_cache,5,[{file,\"/home/vagrant/2018-05-23_14-41-38/scripts/mongooseim/rpm/mongooseim/_build/default/lib/nklib/src/nklib_config.erl\"},{line,268}]},{nksip_app,start,2,[{file,\"/home/vagrant/2018-05-23_14-41-38/scripts/mongooseim/rpm/mongooseim/_build/default/lib/nksip/src/nksip_app.erl\"},{line,86}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,273}]}]}}}}}"}

Crash dump is being written to: erl_crash.dump...Kernel pid terminated (application_controller) ({application_start_failure,nksip,{bad_return,{{nksip_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,enoent}},[{nklib_config,make_cache,5,[{file,"/ho
[root@mongooseim-03 mongooseim]# 

```

**Comment by michalwski** [comment] 2018-06-26 12:32
Looks like our `.deb` and `.rpm` have issues with nksip. Thanks for discovering this. We'll try to fix it, I'm not able to promise any dates now.

What you can do now is try compiling from source. You can find instructions on http://mongooseim.readthedocs.io/en/latest/user-guide/How-to-build/ just remember to run
```bash
./tools/configure with-all
```

before

```bash
make real
```

to be sure that all required deps for the Jingle/SIP integration are added to the release.

**Comment by streaps** [comment] 2018-06-26 12:51
Did you mean `make rel` ?

A couple of minutes earlier I just build it with
`./tools/configure with-jingle-sip`

but it still crashes. I'll try `with-all`

**Comment by streaps** [comment] 2018-06-26 14:03
No matter which version I try (packaged or self-compiled) MongooseIM always crashes with mod_jingle_sip enabled.

**Comment by streaps** [comment] 2018-06-26 15:54
[jingle-sip-crash-logs.zip](https://github.com/esl/MongooseIM/files/2137885/jingle-sip-crash-logs.zip)

**Comment by michalwski** [comment] 2018-07-03 09:11
I see that in your `ejabberd.cfg` file you have `mod_jingle_sip` started without any options. This module tries to connect to a SIP proxy passed in the config. If it's not passed the default value `"localhost"` on port `5600` will be used.
In other words, in order to start the module and try it you need to have a running SIP Proxy. 

More details about the module configuration is here: http://mongooseim.readthedocs.io/en/latest/modules/mod_jingle_sip/

**Comment by michalwski** [comment] 2018-07-03 09:47
> But MongooseIM shouldn't crash when the SIP server is offline, should it?

Right, it'd be better not to crash. I agree with that.

> It's port 5060, not 5600 ;) 

True, the default SIP port is 5060. I couldn't use it for "default" port of the SIP proxy, because MongooseIM itself starts a SIP endpoint listening for connection on port 5060. This would mean that Mongoose talks to itself if the port for SIP proxy is not specified.

**Comment by streaps** [comment] 2018-07-03 12:04
Oh, I thought 5600 was a typo. I read the documentation, but always read 5060 (my brain's auto-correction at work).

I'm more familiar with xmpp than I am with sip. Any recommendations for a simple (easy to configure) outbound proxy? I will try repro and sipio...

**Comment by streaps** [comment] 2018-07-03 13:42
... running a sip proxy on the configured port doesn't prevent the crash. I don't see any connection attempts to the sip proxy.

**Comment by michalwski** [comment] 2018-07-04 07:10
What are the crash reports now? The same as previously? What did you use as the SIP proxy?

**Comment by streaps** [comment] 2018-07-04 11:51
Yes, same error. I tried sipio, repro and netcat.

**Comment by michalwski** [comment] 2018-07-05 09:10
Ok, I've found the root cause of these crashes. The fix is in #1960 could you try it?

**Comment by streaps** [comment] 2018-07-05 10:18
It seems to fix it. No crashes, even without a SIP proxy running. I did not test any functionality, just compiled it, added the module to ejabberd.cfg and started MongooseIM. 

netstat shows that the SIP ports are open:
```
[...]
tcp        0      0 0.0.0.0:5600            0.0.0.0:*               LISTEN      152/beam            
[...]
udp        0      0 0.0.0.0:5600            0.0.0.0:*                           152/beam            
```

**Comment by michalwski** [comment] 2018-07-05 10:52
Thanks for the info. The PR has been merged already. I'm closing the issue. Please open new one when/if needed.

**Closed by michalwski** 2018-07-05 10:52 UTC
Labels: community
