### ISSUE TITLE
Crash in mod_vcard.erl when user try set special chars

### ISSUE THREAD

**Issue by vkatsuba** [esl/MongooseIM#2384] opened 2019-07-25 15:26 UTC
MongooseIM version: 3.3.0
Installed from: https://github.com/esl/MongooseIM/tree/3.3.0
Erlang/OTP version: 20

Hi All,

When user try set nickname with special chars like 😊 - the `mod_vcard.erl` is crashed by reason that inside of `mod_vcard.erl` is used `stringprep:tolower/1`, and `stringprep:tolower/1` will return atom `error` for binaries eg: `<<240,159,152,138>>`. The `binary_to_list/1` don't working with atoms, maybe make sense use `cowboy_bstr:to_lower/1` instead of  `stringprep:tolower/1`?
```
cowboy_bstr:to_lower(<<"ABC">>) =:= stringprep:tolower(<<"ABC">>).
true
```
```
cowboy_bstr:to_lower(<<240,159,152,138>>).
<<240,159,152,138>>
```
```
stringprep:tolower(<<240,159,152,138>>).
error
```
P.S. I was created ticket about this issue for `stringprep` - [https://github.com/processone/stringprep/issues/9](https://github.com/processone/stringprep/issues/9)

Cheers!

**Comment by vkatsuba** [comment] 2019-08-07 16:26
Hi All,

Any updates?

Regards,
@vkatsuba

**Comment by fenek** [comment] 2019-08-22 09:50
Hi @vkatsuba 

Let me clarify first - so the problem affects one of vCard fields you're trying to set, right?

**Comment by vkatsuba** [comment] 2019-08-22 09:57
Hi @fenek,

I suppose this can be affects all fields vCard where we can try set special chars.

**Comment by fenek** [comment] 2019-09-02 17:51
This problem may actually manifest in more places in MIM code. You are right, that it should be improved. I have created an internal ticket to fix this issue.

**Comment by vkatsuba** [comment] 2019-09-02 18:03
Hi @fenek, thanks for response

**Comment by fenek** [comment] 2019-12-02 18:33
The issue is resolved in the current master.

**Closed by fenek** 2019-12-02 18:33 UTC
Labels: community, in backlog
