### ISSUE TITLE
Fix resend_unacked_on_reconnection testcase

### ISSUE THREAD

**Issue by arcusfelis** [esl/MongooseIM#1638] opened 2018-01-12 17:10 UTC
This test is broken in master. Find out why and fix.
I would disable it for now in my pull requests.

Version:

```
commit b71e151c463700c992958ed48426ba88afbce157 (minified-js-is-binary)
Author: Konrad Zemek <konrad.zemek@gmail.com>
Date:   Thu Jan 11 01:23:39 2018 +0100

    Fix global distribution tests for Travis (#1612)
    
    * Increase global distrib bounce timer in tests.
    
    * Add retry on mod_global_distrib_receiver listener eaddrinuse.
    
    * Reorder global distrib test opts to increase robustness.
    
    * Fix race in tests through masterful use of sleep.
    
    * Add a limit to global distrib receiver retries.

```

Error:

```erlang
Testing ejabberd_tests.tests.sm_SUITE: Starting test, 29 test cases
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
escalus_new_assert:assert_true failed on line 84
Reason: {{assertion_failed,assert,is_chat_message,...},
 [{escalus_new_assert,...},{...}|...]}
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
----------------------------------------------------
2018-01-12 16:55:02.755
{resend_unacked_on_reconnection,parallel}
{failed,
    {{assertion_failed,assert,is_chat_message,
         [<<"msg-1">>],
         {xmlel,<<"message">>,
             [{<<"from">>,
               <<"bOb2.391400@localhost/escalus-default-resource">>},
              {<<"to">>,<<"alicE2.508070@localhost">>},
              {<<"xml:lang">>,<<"en">>},
              {<<"type">>,<<"chat">>}],
             [{xmlel,<<"body">>,[],[{xmlcdata,<<"msg-3">>}]},
              {xmlel,<<"delay">>,
                  [{<<"xmlns">>,<<"urn:xmpp:delay">>},
                   {<<"from">>,<<"localhost">>},
                   {<<"stamp">>,<<"2018-01-12T16:55:02.608368Z">>}],
                  [{xmlcdata,<<"SM Storage">>}]}]},
         "<message from='bOb2.391400@localhost/escalus-default-resource' to='alicE2.508070@localhost' xml:lang='en' type='chat'><body>msg-3</body><delay xmlns='urn:xmpp:delay' from='localhost' stamp='2018-01-12T16:55:02.608368Z'>SM Storage</delay></message>"},
     [{escalus_new_assert,assert_true,2,
          [{file,"src/escalus_new_assert.erl"},{line,84}]},
      {sm_SUITE,'-resend_unacked_on_reconnection/1-lc$^3/1-3-',1,
          [{file,"sm_SUITE.erl"},{line,364}]},
      {sm_SUITE,resend_unacked_on_reconnection,1,
          [{file,"sm_SUITE.erl"},{line,364}]},
      {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1533}]},
      {test_server,run_test_case_eval1,6,
          [{file,"test_server.erl"},{line,1053}]},
      {test_server,run_test_case_eval,9,
          [{file,"test_server.erl"},{line,985}]}]}}
Testing ejabberd_tests.tests.sm_SUITE: *** FAILED test case 12 of 29 ***
```

Log link https://travis-ci.org/arcusfelis/MongooseIM/jobs/328163271#L3289

**Comment by michalwski** [comment] 2018-11-05 14:37
The test case has been fixed in #2007. The root cause has also been found and described in the PR, it was not fixed yet.

**Closed by michalwski** 2018-11-05 14:37 UTC
Labels: bug, task, tests
