### ISSUE TITLE
Test push_integration_SUITE:muclight_msg_notify_on_fcm_w_click_action sometimes fails

### ISSUE THREAD

**Issue by arcusfelis** [esl/MongooseIM#1688] opened 2018-01-24 14:55 UTC
MongooseIM version: (put the version)
Installed from: (source or pkg)
Erlang/OTP version: (put the version)

```erlang
=== Ended at 2018-01-24 14:00:31
=== Location: {push_integration_SUITE,muclight_msg_notify_on_fcm_w_click_action}
=== Reason: {thrown,
                     {no_push_messages,<<"F9MD4G93AJCL6NHII8JM6888JBBB">>}}
```

What we see in logs:

```erlang
 2018-01-24 14:00:10.229 [error] <0.12533.2>@mod_push_service_mongoosepush:http_notification:114 Unable to communicate to MongoosePush service due to request_timeout
```

Link to test reports

http://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1687/4023/pgsql_mnesia.20.0/big/ct_run.test@travis-job-a932f466-a9c7-4eca-80fb-70f5d2844923.2018-01-24_13.46.14/ejabberd_tests.tests.push_integration_SUITE.logs/run.2018-01-24_14.00.06/push_integration_suite.muclight_msg_notify_on_fcm_w_click_action.27555.html

Maybe we should increase push notification timeout. Or having retry logic.
Having mongoosepush logs uploaded to aws is good too.

**Comment by michalwski** [comment] 2018-06-29 09:52
This was a duplicate of #1764 which is closed.

**Closed** 2018-06-29 09:52 UTC
Labels: bug, ci-errors
