### ISSUE TITLE
"Permission denied" when starting MongooseIM

### ISSUE THREAD

**Issue by allireno** [esl/MongooseIM#2014] opened 2018-07-30 14:48 UTC
MongooseIM version: 3.1.0
Installed from: source
Erlang/OTP version: 21 (erts 10.0)
When trying to run `bin/mongooseim start `to start MongooseIM I receive the following error:
```
bin/mongooseim: line 60: /home/ar910j/MongooseIM/_build/prod/rel/mongooseim/erts-10.0/bin/escript: Permission denied
bin/mongooseim : line 81: /home/ar910j/MongooseIM/_buils/prod/rel/mongooseim/erts-10.0/bin/run_erl: Permission denied
```

This same error appears when trying to run `bin/mongooseimctl status `

Any idea as to why this is happening/ how to go about fixing it?

**Comment by fenek** [comment] 2018-08-01 10:27
Hi @allireno 

We've observed this problem in some environments with OTP 21 but haven't found the root cause yet. The temporary workaround is to `chmod u+x` all the files in `erts-10.0/bin/` inside release directory.

**Comment by fenek** [comment] 2018-08-22 12:25
Fixed by #2037, will be merged soon.

**Comment by fenek** [comment] 2018-08-23 15:18
@allireno Please give the most recent master a try. :)

**Comment by fenek** [comment] 2018-09-03 14:52
Closing. If the issue persists, please reopen.

**Closed by fenek** 2018-09-03 14:52 UTC
Labels: community
