### ISSUE TITLE
mod_mam_odbc_async_pool_writer mysql calls issue

### ISSUE THREAD

**Issue by andrewvmail** [esl/MongooseIM#1231] opened 2017-03-17 00:06 UTC
MongooseIM version: (detached from 2.0.0) 1743443 Merge pull request #1069 from esl/rel-2.0
Installed from: source
Erlang/OTP version: 18

I use below config and getting errors when ever I am sending a message. I know the credentials for mysql is correct because privacy list function is working and Mongoose is reading and writing to the database. Just when mod_mam_odbc_async_pool_writer do the mysql calls it doesnt like it ...
```
%% https://mongooseim.readthedocs.io/en/2.0.0beta2/modules/mod_mam/

  %% STEP 1
  {mod_mam, []},
  {mod_mam_odbc_arch, [no_writer]},

  {mod_mam_muc, [{host, "muclight.@HOST@"}]},
  {mod_mam_muc_odbc_arch, [no_writer]},

  %% STEP 2
  {mod_mam_odbc_user, [muc, pm]},

  %% STEP 3
  {mod_mam_cache_user, [muc, pm]},

  %% STEP 4
  {mod_mam_odbc_prefs, [muc, pm]},

  %% STEP 5
  {mod_mam_odbc_async_pool_writer, [pm]},

  %% STEP 6
  {mod_mam_muc_odbc_async_pool_writer, [muc]}

```

```
==> /root/MongooseIM/rel/mongooseim/log/crash.log <==
2017-03-16 19:55:45 =CRASH REPORT====
  crasher:
    initial call: gen:init_it/6
    pid: <0.649.0>
    registered_name: []
    exception exit: {closed,[{p1_fsm,terminate,8,[{file,"src/p1_fsm.erl"},{line,760}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
    ancestors: ['momomobile88.com_0',mod_mam_sup,ejabberd_sup,<0.217.0>]
    messages: []
    links: [<0.648.0>]
    dictionary: [{ejabberd_odbc_state,{state,<0.650.0>,mysql,30000,<<"momomobile88.com">>,<0.648.0>,true,1000,{0,{[],[]}}}},{'$internal_queue_len',0},{mim_odbc_dedicated,true},{mim_process_type,odbc_worker},{mim_host,<<"momomobile88.com">>},{ejabberd_odbc_nesting_level,0}]
    trap_exit: true
    status: running
    heap_size: 6772
    stack_size: 27
    reductions: 11999
  neighbours:
    neighbour: [{pid,<0.648.0>},{registered_name,'momomobile88.com_0'},{initial_call,{mod_mam_odbc_async_pool_writer,init,['Argument__1']}},{current_function,{gen_server,loop,6}},{ancestors,[mod_mam_sup,ejabberd_sup,<0.217.0>]},{messages,[]},{links,[<0.649.0>,<0.388.0>]},{dictionary,[]},{trap_exit,false},{status,waiting},{heap_size,376},{stack_size,9},{reductions,2220}]

==> /root/MongooseIM/rel/mongooseim/log/erlang.log.1 <==
2017-03-16 19:55:45.799 [error] <0.649.0> gen_fsm <0.649.0> in state session_established terminated with reason: closed

==> /root/MongooseIM/rel/mongooseim/log/ejabberd.log <==
2017-03-16 19:55:45.799 [error] <0.649.0> CRASH REPORT Process <0.649.0> with 1 neighbours exited with reason: closed in p1_fsm:terminate/8 line 760

==> /root/MongooseIM/rel/mongooseim/log/crash.log <==
2017-03-16 19:55:45 =SUPERVISOR REPORT====
     Supervisor: {local,mod_mam_sup}
     Context:    child_terminated
     Reason:     closed
     Offender:   [{pid,<0.648.0>},{id,'momomobile88.com_0'},{mfargs,{mod_mam_odbc_async_pool_writer,start_link,['momomobile88.com_0',0,<<"momomobile88.com">>]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]


==> /root/MongooseIM/rel/mongooseim/log/erlang.log.1 <==

==> /root/MongooseIM/rel/mongooseim/log/ejabberd.log <==
2017-03-16 19:55:45.800 [error] <0.388.0> Supervisor mod_mam_sup had child 'momomobile88.com_0' started with mod_mam_odbc_async_pool_writer:start_link('momomobile88.com_0', 0, <<"momomobile88.com">>) at <0.648.0> exit with reason closed in context child_terminated

==> /root/MongooseIM/rel/mongooseim/log/erlang.log.1 <==
2017-03-16 19:55:45.799 [error] <0.649.0> CRASH REPORT Process <0.649.0> with 1 neighbours exited with reason: closed in p1_fsm:terminate/8 line 760
2017-03-16 19:55:45.800 [error] <0.388.0> Supervisor mod_mam_sup had child 'momomobile88.com_0' started with mod_mam_odbc_async_pool_writer:start_link('momomobile88.com_0', 0, <<"momomobile88.com">>) at <0.648.0> exit with reason closed in context child_terminated
2017-03-16 19:55:45.801 [debug] <0.388.0> Supervisor mod_mam_sup started mod_mam_odbc_async_pool_writer:start_link('momomobile88.com_0', 0, <<"momomobile88.com">>) at pid <0.1315.0>
2017-03-16 19:55:45.828 [debug] <0.1317.0>@ejabberd_odbc:log:750 mysql_conn: greeting version <<"5.5.47-MariaDB">> (protocol 10) salt <<"d%%+Gb83">> caps 63487 serverchar <<8,2,0,15,160,21,0,0,0,0,0,0,0,0,0,0>> salt2 <<"3HO6^Y\"<H5pS">>
2017-03-16 19:55:45.829 [debug] <0.1317.0>@ejabberd_odbc:log:750 mysql_auth send packet 1: <<7,162,0,0,64,66,15,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,114,111,111,116,0,20,0,129,65,67,81,12,215,154,152,80,91,50,12,53,164,80,244,28,218,181>>

==> /root/MongooseIM/rel/mongooseim/log/ejabberd.log <==
2017-03-16 19:55:45.801 [debug] <0.388.0> Supervisor mod_mam_sup started mod_mam_odbc_async_pool_writer:start_link('momomobile88.com_0', 0, <<"momomobile88.com">>) at pid <0.1315.0>
2017-03-16 19:55:45.828 [debug] <0.1317.0>@ejabberd_odbc:log:750 mysql_conn: greeting version <<"5.5.47-MariaDB">> (protocol 10) salt <<"d%%+Gb83">> caps 63487 serverchar <<8,2,0,15,160,21,0,0,0,0,0,0,0,0,0,0>> salt2 <<"3HO6^Y\"<H5pS">>
2017-03-16 19:55:45.829 [debug] <0.1317.0>@ejabberd_odbc:log:750 mysql_auth send packet 1: <<7,162,0,0,64,66,15,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,114,111,111,116,0,20,0,129,65,67,81,12,215,154,152,80,91,50,12,53,164,80,244,28,218,181>>
```

```
==> /root/MongooseIM/rel/mongooseim/log/ejabberd.log <==
2017-03-16 20:03:30.392 [error] <0.1429.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}

==> /root/MongooseIM/rel/mongooseim/log/crash.log <==
2017-03-16 20:03:30 =ERROR REPORT====
mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}

==> /root/MongooseIM/rel/mongooseim/log/ejabberd.log <==
2017-03-16 20:03:30.392 [error] <0.1405.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.392 [error] <0.1403.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.393 [error] <0.1426.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.393 [error] <0.1399.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.393 [error] <0.1424.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.393 [error] <0.1401.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.393 [error] <0.1422.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.393 [error] <0.1418.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.393 [error] <0.1416.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.394 [error] <0.1395.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.394 [error] <0.1414.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.394 [error] <0.1397.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.395 [error] <0.1393.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.395 [error] <0.1391.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.395 [error] <0.1496.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.395 [error] <0.1494.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.395 [error] <0.1492.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.395 [error] <0.1488.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.395 [error] <0.1486.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.396 [error] <0.1484.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.396 [error] <0.1482.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.396 [error] <0.1480.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.396 [error] <0.1478.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.396 [error] <0.1436.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.396 [error] <0.1434.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.396 [error] <0.1490.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.397 [error] <0.1432.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.397 [error] <0.1476.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.397 [error] <0.1474.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.397 [error] <0.1472.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.397 [error] <0.1464.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.397 [error] <0.1470.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.397 [error] <0.1468.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.397 [error] <0.1466.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.398 [error] <0.1462.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.398 [error] <0.1460.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.398 [error] <0.1456.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.398 [error] <0.1458.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.398 [error] <0.1454.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
2017-03-16 20:03:30.398 [error] <0.1452.0> mysql_recv:111, failed connecting to "mau.momodatabase.com":3306, reason: {error,econnrefused}
```

**Comment by andrewvmail** [comment] 2017-03-17 00:39
It turned out that the database server ran out of space! 40GB of mam_message in a test server. Not sure what is causing this. Maybe a loop?

**Comment by michalwski** [comment] 2017-03-17 07:53
Hi @andrewvmail,

There can be plenty of reasons for this issue. It's hard to guess without knowing the test scenario and looking inside the database. You try analysing `mam-related` tables in MySQL to see who talked with whom. This could help you determine if there was a loop or not.

Talking about loops, we recently fixed some bugs related to race conditions which could potentially create many message in MAM. Please take a look at this patches:
* #1141 - this one is included in MongooseIM 2.0.1
* #1186 - this one is merged into master, but there is no release with this patch yet.

**Comment by andrewvmail** [comment] 2017-03-17 08:05
@michalslaski I'm also noticing everything is saved in mam_message and nothing is saved in mam_muc_message. Not sure if this is related or a different issue. I will use the latest version and see if problem persist.

**Comment by michalwski** [comment] 2017-03-17 08:15
I've just noticed that you commented on issue: #827. I understand you are using MUC light, am I right? If so then this is most probably the reason why you have so many message in MAM. Currently MongooseIM copies MAM messages to user archives. This increases the amount of stored data, on the other hand gives you better privacy of conversation. With this approach users can see only these room messages which were sent to room when they were subscribed to it. I agree this is not always wanted behaviour and it'd be good to make it configurable. I'll make sure this is included in coming release.

**Comment by michalwski** [comment] 2017-05-29 08:40
All right, the root cause (as I understand it) of this issue is fix. Please re-open the issue if there's sth else.

**Closed by michalwski** 2017-05-29 08:40 UTC
