### ISSUE TITLE
Redis and MongooseIM going crazy

### ISSUE THREAD

**Issue by andrewvmail** [esl/MongooseIM#1082] opened 2016-11-20 02:29 UTC
MongooseIM version: 1.6.2-957-gb13807d
Installed from: source
Erlang/OTP version: 18

Hello starting few days ago my lab installation of MongooseIM is running at 70% and its chatting with redis non stop for some reason. I tcpdump the traffic and just dump the pcap into vim and below is a slice of what i see in vim. Been running half year and just starting to see this.

No one is connected to it... and both redis and mongoose is running heavy.

Any ideas?

```
M<+ÿÿÿÿÿÿÿÿ-Mac OS X 10.11.5, build 15F34 (Darwin 15.5.0);Dumpcap (Wireshark) 1.99.8 (v1.99.8-0-ga0c561a from master)\ÿÿ-	-Mac OS X 10.11.5, build 15F34 (Darwin 15.5.0)\À±AFH^ðÌÂ×ÌEy@@
º
§H »¢§>8xÂÇ9Ö
¦	Òh)Ù×*2
$8
SMEMBERS
$64
s3:u17785555555:momoterramobile.com:FEA757CE3F89D301479347923582361

À±AÝJ^ðhhÌÌÂ×EZÕ^@@*ë

º »§H8xÂ¢§!v,
h)Ùò¦	Ò*1
$282
hdsessionhhbÇbOb	Ägdmongooseim@localhost+2hmu17785555555mmomoterramobile.commFEA757CE3F89D301479347923582361hmu17785555555mmomoterramobile.comd	undefinedlhdauth_modulemhdccd	undefinedhdconndunknownhdiphhaÏaÂaaÏbíÏj
À±AÓS^ðÌÂ×ÌE|¶@@^
º
` »PwçxÓÈ9Ö
¦	Õh)ÙÙ*2
$8
SMEMBERS
$64
s3:u17785555555:momoterramobile.com:FEA757CE3F89D301479347923582361

À±AU^ðhhÌÌÂ×EZh	@@@

º »`ÓPwçÓ`µ
h)Ùõ¦	Õ*1
$282
hdsessionhhbÇbOb	Ägdmongooseim@localhost+2hmu17785555555mmomoterramobile.commFEA757CE3F89D301479347923582361hmu17785555555mmomoterramobile.comd	undefinedlhdauth_modulemhdccd	undefinedhdconndunknownhdiphhaÏaÂaaÏbíÏj
À±AZ^ðÌÂ×ÌEÈ4@@8à
º
§ »_n>ÉhiLÈ9Ö
¦	Öh)ÙÚ*2
$8
SMEMBERS
$64
s3:u17785555555:momoterramobile.com:FEA757CE3F89D301479347923582361

À±A[^ðhhÌÌÂ×EZL@@üý

º »§hiL_n?$ð
h)Ùö¦	Ö*1
$282
hdsessionhhbÇbOb	Ägdmongooseim@localhost+2hmu17785555555mmomoterramobile.commFEA757CE3F89D301479347923582361hmu17785555555mmomoterramobile.comd	undefinedlhdauth_modulemhdccd	undefinedhdconndunknownhdiphhaÏaÂaaÏbíÏj
À±A_^ðÌÂ×ÌEz@@
º
§H »¢§8xèÇ9Ö
¦	Øh)Ùò*2
$8
SMEMBERS
$64
s3:u17785555555:momoterramobile.com:FEA757CE3F89D301479347923582361

À±A§`^ðhhÌÌÂ×EZÕ_@@*ê

º »§H8xè¢§ô!t
h)Ùø¦	Ø*1
$282
hdsessionhhbÇbOb	Ägdmongooseim@localhost+2hmu17785555555mmomoterramobile.commFEA757CE3F89D301479347923582361hmu17785555555mmomoterramobile.comd	undefinedlhdauth_modulemhdccd	undefinedhdconndunknownhdiphhaÏaÂaaÏbíÏj
À±Awd^ðÌÂ×ÌE|·@@]
º
` »PwçÓÓ¯È9Ö
¦	Ùh)Ùõ*2
$8
SMEMBERS
```

**Comment by michalwski** [comment] 2016-11-21 09:21
Hi @andrewvmail 

Thanks for contacting us. You have very intriguing  issue. Is it possible for you to connect to MongooseIM debug console `mongooseim debug` (you may need to prefix `mongooseim` with the path to the script) and setup recon tracing similar to this one:

```erlang
recon_trace:calls({ejabberd_sm, '_', fun(_) -> return_trace() end}, 500).
```

This will setup tracing for all public functions in `ejabberd_sm` module. This tracing will be finished after 500 functions. The output of the tracing you should see on your console.

**Comment by andrewvmail** [comment] 2016-11-22 18:34
@michalslaski 

I restarted it but I will do the above if this happens again.

Thanks!

**Comment by andrewvmail** [comment] 2016-11-26 01:15
Hi @michalslaski 

it is happening again... also I couldnt paste everything in github because of the character limit. 

But here is the pastebin of the log

http://pastebin.com/gjQNGf28

**Comment by andrewvmail** [comment] 2016-12-13 18:55
@michalslaski 

Just wondering if you have had a look at this, the server just started acting up again yesterday...

Thanks in advance.

**Comment by andrewvmail** [comment] 2016-12-14 01:11
Just want to add some observation I made today regarding this issue. 

There was some rogue session in Redis of the same user 2-3 entries and from the ejabberd.log the server is busy outputting presence stanza of that user to each other. I believe the server is sending presence loop? 

Without killing the mongooseim process. I went to redis and just del the those rogue session and and the loop stop and everything goes back to normal...

I tried to replicate the issue by connecting and disconnecting the clients but to no avail.

**Comment by michalwski** [comment] 2016-12-14 07:48
Thanks for the update and my apologies for not responding earlier. From the previous trace you attached I can see that there is a lot of carbon copy messages to the same user (from probably the same user). Also I can see that many of these messages comes from stream management buffer and offline storage. To identify the root cause I would need to know more details about your client application. I can understand that you may not want to share this information publicly.

**Comment by andrewvmail** [comment] 2016-12-14 20:05
@michalwski Thanks for getting back to me. We made an executive decision instead of using strophejs to use stanza with kaiwa/otalk being the reference client. I know Stanza is what you guys use in the labs? And I found about the options mod_ping yesterday  with killtimeout options set. Maybe with that on and the move to stanza the server will do a better job killing rogue sessions.

**Comment by andrewvmail** [comment] 2016-12-15 20:04
Hi @michalwski ,

We are still seeing this issue, even with the ``` {mod_ping, [{send_pings, true}, {ping_interval, 240}, {timeout_action, kill}]}, ```
Our frontend developer was developing using https://github.com/digicoop/kaiwa client and MongooseIM server tag 2.0.0 with archive using mysql and session using redis, http_auth enabled.

Inspecting redis through ``` keys * ``` is still showing rogue session not getting cleaned up.

There is still the stanza loop between the same user (the user that frontend developer was using). Any other ideas? This happened while our frontend developer was developing, so he was frequently connecting to the server multiple times.

Inspecting redis through ``` keys * ``` is still showing rogue session not getting cleaned up.

Thanks in advance
A

**Comment by michalwski** [comment] 2017-01-04 14:26
Hi @andrewvmail,

It's most probably a race condition. This PR #1141 should fix the issue. Is it possible for you to try this patch and get us your feedback?

**Comment by michalwski** [comment] 2017-01-13 10:21
The PR with the fix for this issue has just been merged. I'm closing this issue. Please re-open when you check new code and notice the infinite loop again.

**Closed by michalwski** 2017-01-13 10:21 UTC

**Comment by andrewvmail** [comment] 2017-01-13 10:55
Thanka Michal, I havent seen the problem so I think all os good
