### ISSUE TITLE
Cannot start mongooseim

### ISSUE THREAD

**Issue by suyesh-amatya** [esl/MongooseIM#2487] opened 2019-10-10 12:35 UTC
MongooseIM version: (3.4.0)
Installed from: (mongooseim_3.4.0-1~centos~7_amd64.rpm)
Erlang/OTP version: (10.3.5.1 ?)

### Cannot start mongooseim. 
```
$mongooseimctl live

Root: //usr/lib/mongooseim
Exec: //usr/lib/mongooseim/erts-10.3.5.1/bin/erlexec -boot //usr/lib/mongooseim/releases/3.4.0/mongooseim -embedded -config //etc/mongooseim/app.config -args_file //etc/mongooseim/vm.args -args_file //etc/mongooseim/vm.dist.args -- console
Erlang/OTP 21 [erts-10.3.5.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:5] [hipe]

=INFO REPORT==== 10-Oct-2019::14:29:06.251155 ===
    msg: Starting reporters with []

    options: []
14:29:06.259 [info] msg: "Starting reporters with []\n", options: []
14:29:06.440 [notice] Changed loglevel of /var/log/mongooseim/ejabberd.log to info
14:29:06.483 [info] Application mnesia exited with reason: stopped
14:29:06.816 [notice] Changed loglevel of /var/log/mongooseim/ejabberd.log to warning
14:29:07.220 [error] CRASH REPORT Process <0.1149.0> with 0 neighbours exited with reason: no match of right hand value {error,eperm} in nkpacket_stun:check_stun_server/5 line 277 in application_master:init/4 line 138
{"Kernel pid terminated",application_controller,"{application_start_failure,nkpacket,{bad_return,{{nkpacket_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,eperm}},[{nkpacket_stun,check_stun_server,5,[{file,\"/root/rpm/mongooseim/_build/default/lib/nkpacket/src/nkpacket_stun.erl\"},{line,277}]},{nkpacket_stun,get_stun_servers,4,[{file,\"/root/rpm/mongooseim/_build/default/lib/nkpacket/src/nkpacket_stun.erl\"},{line,261}]},{nkpacket_stun,get_stun_servers,1,[{file,\"/root/rpm/mongooseim/_build/default/lib/nkpacket/src/nkpacket_stun.erl\"},{line,97}]},{nkpacket_stun,ext_ip,1,[{file,\"/root/rpm/mongooseim/_build/default/lib/nkpacket/src/nkpacket_stun.erl\"},{line,75}]},{nkpacket_app,get_auto_ips,0,[{file,\"/root/rpm/mongooseim/_build/default/lib/nkpacket/src/nkpacket_app.erl\"},{line,113}]},{nkpacket_app,start,2,[{file,\"/root/rpm/mongooseim/_build/default/lib/nkpacket/src/nkpacket_app.erl\"},{line,58}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,277}]}]}}}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,nkpacket,{bad_return,{{nkpacket_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,eperm}},[{nkpacket_stun,check_stun_server,5,

Crash dump is being written to: erl_crash.dump...
```

### ejabberd.log
```
2019-10-10 14:29:06.259 [info] <0.234.0> msg: "Starting reporters with []\n", options: []
2019-10-10 14:29:06.440 [notice] <0.97.0>@lager_file_backend:141 Changed loglevel of /var/log/mongooseim/ejabberd.log to info
2019-10-10 14:29:06.483 [info] <0.43.0> Application mnesia exited with reason: stopped
2019-10-10 14:29:07.220 [error] <0.1149.0>@nkpacket_stun:check_stun_server:277 CRASH REPORT Process <0.1149.0> with 0 neighbours exited with reason: no match of right hand value {error,eperm} in nkpacket_stun:check_stun_server/5 line 277 in application_master:init/4 line 138
```

```
$mongooseimctl start
$mongooseimctl status

Failed RPC connection to the node mongooseim@localhost: nodedown
```

**Comment by fenek** [comment] 2019-10-15 09:22
Hi @suyesh-amatya 

This issue is caused by the startup of Jingle/SIP module, which is unable to connect to a public STUN server due to permission error. For now the only possible solutions are either to change OS policy to allow such UDP connections, or compile MongooseIM from source, which is by default built without Jingle/SIP support.

**Comment by fenek** [comment] 2019-10-28 12:54
@suyesh-amatya 

Has my comment helped you in resolving the issue? :)

**Comment by suyesh-amatya** [comment] 2019-11-06 07:37
Hi! Yes it was due to the permissions policies in the OS and the firewall. We had to open certain ports and whitelist network traffic.

Thanks for the help!
/Suyesh

Skaffa Outlook för Android<https://aka.ms/ghei36>

________________________________

**Comment by fenek** [comment] 2019-11-06 16:16
You're welcome. :)

**Closed by fenek** 2019-11-06 16:16 UTC
Labels: community
