### ISSUE TITLE
Push-enabling causes repeated MongooseIM crashes

### ISSUE THREAD

**Issue by pbhowmic** [esl/MongooseIM#1639] opened 2018-01-13 22:24 UTC
MongooseIM version: 2.1.0
Installed from: erlang solutions
Erlang/OTP version: esl-erlang 1:20.2.2

I am running a fairly standard MongooseIM server on Ubuntu Xenial in GCE with these standouts:-
Push messaging enabled and my client is Android-based with and uses the smack library and SSL/TLS disabled (for now). Bear with me as I try & describe this issue the best I can and please ask for more info as needed.
1. The following 3 are served by the same domain _X_ and MongooseIM instance.

- mod_push
- mod_pubsub
- mod_push_service_mongoosepush

2. The MongoosePush component is running as a docker container in the same GCE instance as the above and the subdomain _pubsub.X_ resolves to the same GCE host.
3. I have http authentication turned on.

The following is my ejabberd.cfg file (comments/blank lines stripped out)

```
{loglevel, 3}.
{hosts, ["chat-dev.idocrx.com"] }.
{listen,
 [
  { 5280, ejabberd_cowboy, [
      {num_acceptors, 10},
      {transport_options, [{max_connections, 1024}]},
      {modules, [
          {"_", "/http-bind", mod_bosh},
          {"_", "/ws-xmpp", mod_websockets, [{ejabberd_service, [
                                        {access, all},
                                        {shaper_rule, fast},
                                        {ip, {127, 0, 0, 1}},
                                        {password, "secret"}]}
          ]}
      ]}
  ]},
  { 5285, ejabberd_cowboy, [
        {num_acceptors, 10},
        {transport_options, [{max_connections, 1024}]},
        {ssl, [{certfile, "priv/ssl/fake_cert.pem"}, {keyfile, "priv/ssl/fake_key.pem"}, {password, ""}]},
        {modules, [
            {"_", "/http-bind", mod_bosh},
            {"_", "/ws-xmpp", mod_websockets, [
            ]}
        ]}
    ]},
  { {8088, "10.142.0.2"} , ejabberd_cowboy, [
      {num_acceptors, 10},
      {transport_options, [{max_connections, 1024}]},
      {modules, [
          {"10.142.0.2", "/api", mongoose_api_admin, []}
      ]}
  ]},
  { 8089 , ejabberd_cowboy, [
      {num_acceptors, 10},
      {transport_options, [{max_connections, 1024}]},
      {protocol_options, [{compress, true}]},
      {ssl, [{certfile, "priv/ssl/fake_cert.pem"}, {keyfile, "priv/ssl/fake_key.pem"}, {password, ""}]},
      {modules, [
          {"_", "/api/sse", lasse_handler, [mongoose_client_api_sse]},
          {"_", "/api/messages/[:with]", mongoose_client_api_messages, []},
          {"_", "/api/rooms/[:id]",    mongoose_client_api_rooms, []},
          {"_", "/api/rooms/:id/users/[:user]",    mongoose_client_api_rooms_users, []},
          {"_", "/api/rooms/[:id]/messages",    mongoose_client_api_rooms_messages, []}
      ]}
  ]},
  { {5288, "127.0.0.1"} , ejabberd_cowboy, [
      {num_acceptors, 10},
      {transport_options, [{max_connections, 1024}]},
      {modules, [
          {"localhost", "/api", mongoose_api, [{handlers, [mongoose_api_metrics,
                                                           mongoose_api_users]}]}
      ]}
  ]},
  { 5222, ejabberd_c2s, [
			{access, c2s},
			{shaper, c2s_shaper},
			{max_stanza_size, 65536},
			{protocol_options, ["no_sslv3"]}
                        
		       ]},
  
  { 5269, ejabberd_s2s_in, [
			   {shaper, s2s_shaper},
			   {max_stanza_size, 131072},
			   {protocol_options, ["no_sslv3"]}
			   
			  ]}
  ,{8888, ejabberd_service, [
                {access, all},
                {shaper_rule, fast},
                {ip, {127, 0, 0, 1}},
                {password, "secret"}
           ]}
 ]}.
{s2s_use_starttls, optional}.
{s2s_certfile, "priv/ssl/fake_server.pem"}.
{s2s_default_policy, deny }.
{outgoing_s2s_port, 5269 }.
{sm_backend, {mnesia, []} }.
{auth_method, http}.
{auth_password_format, plain}.
{auth_opts, [
             
             
             {host, "http://www.idocrx.com"}, 
             {connection_pool_size, 10},  % default
             {is_external, true},
             {path_prefix, "/xmpp/auth/"} % default
            ]}.
{http_connections, [{mongoose_push_http, [{server, "https://localhost:8443"}] }]}.
{shaper, normal, {maxrate, 1000}}.
{shaper, fast, {maxrate, 50000}}.
{max_fsm_queue, 1000}.
{acl, local, {user_regexp, ""}}.
{access, max_user_sessions, [{10, all}]}.
{access, max_user_offline_messages, [{5000, admin}, {100, all}]}.
{access, local, [{allow, local}]}.
{access, c2s, [{deny, blocked},
	       {allow, all}]}.
{access, c2s_shaper, [{none, admin},
		      {normal, all}]}.
{access, s2s_shaper, [{fast, all}]}.
{access, muc_admin, [{allow, admin}]}.
{access, muc_create, [{allow, local}]}.
{access, muc, [{allow, all}]}.
{access, register, [{allow, all}]}.
{registration_timeout, infinity}.
{access, mam_set_prefs, [{default, all}]}.
{access, mam_get_prefs, [{default, all}]}.
{access, mam_lookup_messages, [{default, all}]}.
{access, mam_purge_single_message, [{default, all}]}.
{access, mam_purge_multiple_messages, [{default, all}]}.
{shaper, mam_shaper, {maxrate, 1}}.
{shaper, mam_global_shaper, {maxrate, 1000}}.
{access, mam_set_prefs_shaper, [{mam_shaper, all}]}.
{access, mam_get_prefs_shaper, [{mam_shaper, all}]}.
{access, mam_lookup_messages_shaper, [{mam_shaper, all}]}.
{access, mam_purge_single_message_shaper, [{mam_shaper, all}]}.
{access, mam_purge_multiple_messages_shaper, [{mam_shaper, all}]}.
{access, mam_set_prefs_global_shaper, [{mam_global_shaper, all}]}.
{access, mam_get_prefs_global_shaper, [{mam_global_shaper, all}]}.
{access, mam_lookup_messages_global_shaper, [{mam_global_shaper, all}]}.
{access, mam_purge_single_message_global_shaper, [{mam_global_shaper, all}]}.
{access, mam_purge_multiple_messages_global_shaper, [{mam_global_shaper, all}]}.
{language, "en"}.
{all_metrics_are_global, false }.
{modules,
 [
  {mod_adhoc, []},
 {mod_push, [ {wpool, [{workers, 100}]} ]},    
  {mod_push_service_mongoosepush, [ {pool_name, mongoose_push_http}, {api_version, "v2"} ]},
  {mod_pubsub, [ {plugins, [<<"push">>]} ]}, 
  {mod_disco, []},
  {mod_commands, []},
  {mod_muc_commands, []},
  {mod_muc_light_commands, []},
  {mod_last, []},
  {mod_stream_management, [
                          ]},
  {mod_offline, [{access_max_user_messages, max_user_offline_messages}]},
  {mod_privacy, []},
  {mod_blocking, []},
  {mod_private, []},
  {mod_register, [
		  {welcome_message, {""}},
		  {ip_access, [{allow, "127.0.0.0/8"},
			       {deny, "0.0.0.0/0"}]},
		  {access, register}
		 ]},
  {mod_roster, []},
  {mod_sic, []},
  {mod_vcard, [%{matches, 1},
{host, "vjud.@HOST@"}
]},
  {mod_bosh, []},
  {mod_carboncopy, []},
  {mod_ping, [{send_pings, true}]}
]}.

```

The last crash produced this erlang.log file 
```
=====
===== LOGGING STARTED Thu Jan 11 08:17:47 UTC 2018
=====
2018-01-11 08:17:47.665 [error] <0.769.0>@ejabberd_hooks:run_fold1:263 {{case_clause,<<"error">>},[{mod_push_plugin_default,sender_id,2,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push_plugin_default.erl"},{line,51}]},{mod_push,push_notification_iq,5,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,257}]},{mod_push,'-publish_message/4-fun-3-',7,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,181}]},{lists,foreach,2,[{file,"lists.erl"},{line,1338}]},{mod_push,publish_message,4,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,179}]},{mod_push,filter_packet,1,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,124}]},{safely,apply,3,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/safely.erl"},{line,19}]},{ejabberd_hooks,hook_apply_function,5,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/ejabberd_hooks.erl"},{line,277}]}]}
running hook: {filter_local_packet,[]}
2018-01-11 08:17:47.828 [error] <0.687.0>@ejabberd_hooks:run_fold1:263 {{case_clause,<<"error">>},[{mod_push_plugin_default,sender_id,2,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push_plugin_default.erl"},{line,51}]},{mod_push,push_notification_iq,5,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,257}]},{mod_push,'-publish_message/4-fun-3-',7,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,181}]},{lists,foreach,2,[{file,"lists.erl"},{line,1338}]},{mod_push,publish_message,4,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,179}]},{mod_push,filter_packet,1,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,124}]},{safely,apply,3,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/safely.erl"},{line,19}]},{ejabberd_hooks,hook_apply_function,5,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/ejabberd_hooks.erl"},{line,277}]}]}
running hook: {filter_local_packet,[]}
2018-01-11 08:17:48.103 [error] <0.681.0>@ejabberd_hooks:run_fold1:263 {{case_clause,<<"error">>},[{mod_push_plugin_default,sender_id,2,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push_plugin_default.erl"},{line,51}]},{mod_push,push_notification_iq,5,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,257}]},{mod_push,'-publish_message/4-fun-3-',7,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,181}]},{lists,foreach,2,[{file,"lists.erl"},{line,1338}]},{mod_push,publish_message,4,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,179}]},{mod_push,filter_packet,1,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,124}]},{safely,apply,3,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/safely.erl"},{line,19}]},{ejabberd_hooks,hook_apply_function,5,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/ejabberd_hooks.erl"},{line,277}]}]}
running hook: {filter_local_packet,[]}
2018-01-11 08:17:48.109 [error] <0.686.0>@ejabberd_hooks:run_fold1:263 {{case_clause,<<"error">>},[{mod_push_plugin_default,sender_id,2,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push_plugin_default.erl"},{line,51}]},{mod_push,push_notification_iq,5,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,257}]},{mod_push,'-publish_message/4-fun-3-',7,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,181}]},{lists,foreach,2,[{file,"lists.erl"},{line,1338}]},{mod_push,publish_message,4,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,179}]},{mod_push,filter_packet,1,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,124}]},{safely,apply,3,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/safely.erl"},{line,19}]},{ejabberd_hooks,hook_apply_function,5,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/ejabberd_hooks.erl"},{line,277}]}]}
running hook: {filter_local_packet,[]}
2018-01-11 08:17:48.337 [error] <0.769.0>@ejabberd_hooks:run_fold1:263 {{case_clause,<<"error">>},[{mod_push_plugin_default,sender_id,2,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push_plugin_default.erl"},{line,51}]},{mod_push,push_notification_iq,5,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,257}]},{mod_push,'-publish_message/4-fun-3-',7,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,181}]},{lists,foreach,2,[{file,"lists.erl"},{line,1338}]},{mod_push,publish_message,4,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,179}]},{mod_push,filter_packet,1,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,124}]},{safely,apply,3,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/safely.erl"},{line,19}]},{ejabberd_hooks,hook_apply_function,5,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/ejabberd_hooks.erl"},{line,277}]}]}
running hook: {filter_local_packet,[]}
2018-01-11 08:17:48.339 [error] <0.681.0>@ejabberd_hooks:run_fold1:263 {{case_clause,<<"error">>},[{mod_push_plugin_default,sender_id,2,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push_plugin_default.erl"},{line,51}]},{mod_push,push_notification_iq,5,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,257}]},{mod_push,'-publish_message/4-fun-3-',7,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,181}]},{lists,foreach,2,[{file,"lists.erl"},{line,1338}]},{mod_push,publish_message,4,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,179}]},{mod_push,filter_packet,1,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,124}]},{safely,apply,3,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/safely.erl"},{line,19}]},{ejabberd_hooks,hook_apply_function,5,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/ejabberd_hooks.erl"},{line,277}]}]}
running hook: {filter_local_packet,[]}
2018-01-11 08:17:48.463 [error] <0.687.0>@ejabberd_hooks:run_fold1:263 {{case_clause,<<"error">>},[{mod_push_plugin_default,sender_id,2,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push_plugin_default.erl"},{line,51}]},{mod_push,push_notification_iq,5,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,257}]},{mod_push,'-publish_message/4-fun-3-',7,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,181}]},{lists,foreach,2,[{file,"lists.erl"},{line,1338}]},{mod_push,publish_message,4,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,179}]},{mod_push,filter_packet,1,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,124}]},{safely,apply,3,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/safely.erl"},{line,19}]},{ejabberd_hooks,hook_apply_function,5,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/ejabberd_hooks.erl"},{line,277}]}]}
running hook: {filter_local_packet,[]}
2018-01-11 08:17:48.675 [error] <0.686.0>@ejabberd_hooks:run_fold1:263 {{case_clause,<<"error">>},[{mod_push_plugin_default,sender_id,2,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push_plugin_default.erl"},{line,51}]},{mod_push,push_notification_iq,5,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,257}]},{mod_push,'-publish_message/4-fun-3-',7,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,181}]},{lists,foreach,2,[{file,"lists.erl"},{line,1338}]},{mod_push,publish_message,4,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,179}]},{mod_push,filter_packet,1,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/mod_push.erl"},{line,124}]},{safely,apply,3,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/safely.erl"},{line,19}]},{ejabberd_hooks,hook_apply_function,5,[{file,"/home/vagrant/2017-11-20_12-04-04/scripts/mongooseim/deb/mongooseim/_build/prod/lib/ejabberd/src/ejabberd_hooks.erl"},{line,277}]}]}
running hook: {filter_local_packet,[]}
eheap_alloc: Cannot allocate 177423032 bytes of memory (of type "old_heap").

Crash dump is being written to: erl_crash.dump...
===== ALIVE Thu Jan 11 08:37:19 UTC 2018

===== Thu Jan 11 08:51:58 UTC 2018
done

```

**Comment by fenek** [comment] 2018-01-14 14:22
Hi @pbhowmic 

This is a known issue in 2.1.0 and is fixed in current master branch. If you'd like to stick to official releases, 2.1.1 is going to be released on Tuesday.

**Comment by pbhowmic** [comment] 2018-01-14 20:08
Thanks for the prompt reply @fenek. I will wait for the official release since it is so close to release.

**Comment by pbhowmic** [comment] 2018-01-17 21:20
When is 2.1.1 slated for release? I don't see anything on erlang solutions yet.

**Comment by pbhowmic** [comment] 2018-01-23 05:43
Still causing same issue even in 2.1.1, built from source.
I have switched from *mod_push* to *mod_event_pusher_push*, all else remains the same

**Comment by fenek** [comment] 2018-01-24 09:47
Can you please paste errors from a log from 2.1.1 and how you configured `mod_event_pusher`?

**Comment by vkatsuba** [comment] 2018-02-02 16:50
Hi @fenek and @pbhowmic 

I have the same issue - bytes of memory (of type "old_heap"). The approach are not good but I suppose this can help @pbhowmic for some time. So, in ejabberd.cfg or remove or comment out the
mod_ping - {mod_ping, [{send_pings, true}]}
This help me. 

@fenek as I said above, I have the same issue, and when I comment out mod_ping, the issue is not reproduce anymore, but the problem in.. for me mod_ping is important to include in the project. So, do you have any ideas about this? Many thanks.

Cheers

**Comment by GalaxyGorilla** [comment] 2018-02-06 17:03
I don't know yet if this is a MIM issue, but enabling mod_ping with `send_pings` set to `true` is currently wrecking the whole application on some event (no more connections are established, clients will get SSL handshake errors, mongoosectl doesn't work anymore etc.). I will investigate tomorrow further down the road ... you should enable debug logging to probably see something like this:

```
ejabberd.log.4-2018-02-06 17:14:34.465 [debug] mod_mam:filter_packet:312: Receive packet
ejabberd.log.4-    from {jid,<<>>,<<"localhost">>,<<>>,<<>>,<<"localhost">>,<<>>}
ejabberd.log.4-    to {jid,<<"3327652759562541557">>,<<"localhost">>,<<>>,<<"3327652759562541557">>,<<"localhost">>,<<>>}
ejabberd.log.4:    packet {xmlel,<<"iq">>,[{<<"type">>,<<"error">>},{<<"id">>,<<"DB122471727AFECC">>}],[{xmlel,<<"ping">>,[{<<"xmlns">>,<<"urn:xmpp:ping">>}],[]},{xmlel,<<"error">>,[{<<"code">>,<<"400">>},{<<"type">>,<<"modify">>}],[{xmlel,<<"bad-request">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-stanzas">>}],[]}]},{xmlel,<<"error">>,[{<<"code">>,<<"400">>},{<<"type">>,<<"modify">>}],[{xmlel,<<"bad-request">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-stanzas">>}],[]}]},{xmlel,<<"error">>,[{<<"code">>,<<"400">>},{<<"type">>,<<"modify">>}],[{xmlel,<<"bad-request">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-stanzas">>}],[]}]},{xmlel,<<"error">>,[{<<"code">>,<<"400">>},{<<"type">>,<<"modify">>}],[{xmlel,<<"bad-request">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-stanzas">>}],[]}]},{xmlel,<<"error">>,[{<<"code">>,<<"400">>},{<<"type">>,<<"modify">>}],[{xmlel,<<"bad-request">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-stanzas">>}],[]}]},{xmlel,<<"error">>,[{<<"code">>,<<"400">>},{<<"type">>,<<"modify">>}],[{xmlel,<<"bad-request">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-stanzas">>}],[]}]},{xmlel,<<"error">>,[{<<"code">>,<<"400">>},{<<"type">>,<<"modify">>}],[{xmlel,<<"bad-request">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-stanzas">>}],[]}]},{xmlel,<<"error">>,[{<<"code">>,<<"400">>},{<<"type">>,<<"modify">>}],[{xmlel,<<"bad-request">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-stanzas">>}],[]}]},
...
```

But again, maybe this is my own doing since I use a shitload of custom modules. I tested the ping module ~2month ago and it worked fine iirc.

**Comment by GalaxyGorilla** [comment] 2018-02-08 15:48
@fenek This happens when a ping is sent to a JID which has no resource. You can reproduce this bug using:

```
JID = {jid,<<"12345">>,<<"localhost">>,<<"">>,<<"12345">>,<<"localhost">>,<<"">>}.
mod_ping:user_send(undefined, JID, undefined, undefined).
```

Then just wait the configured timespan for pinging clients (by default 60s) and you can watch the app getting wrecked. If you turn on the the debug logs you can see the logs I described. Of course one can check in `mod_ping.erl` for the resource but I think there is something fundamentally flawed in the error handling within MIM.

**Comment by fenek** [comment] 2018-03-15 10:49
The issue with `mod_event_pusher` has been finally resolved by PR #1726 and the problem with `mod_ping` is fixed by PR #1710.

We're going to revisit the automatic IQ error generation as a separate task.

@GalaxyGorilla @vkatsuba @pbhowmic Does the current master solve the issues you've reported?

**Comment by vkatsuba** [comment] 2018-03-15 10:56
Hi @fenek,

Thanks for updates. Unfortunately I didn't dare to update the project so far to the master. But I look to PR and suppose this really can help. If there I will be have updates, I will certainly inform you.

Cheers!

**Comment by GalaxyGorilla** [comment] 2018-03-15 11:44
Hey @fenek, we currently use a fork with the patch provided by @sstrigler (plus stuff related to #1725) and things are working fine. I can't speak for the event pusher. As there is a new milestone I will definitely check out the current master in our test (and probably production) environments soon'ish.

**Comment by fenek** [comment] 2018-06-26 16:42
IQ error handling is fixed in stable MongooseIM release.

**Closed by fenek** 2018-06-26 16:42 UTC
