### ISSUE TITLE
Duplicate messages mod_inbox and push

### ISSUE THREAD

**Issue by krot3232** [esl/MongooseIM#3010] opened 2021-01-15 15:29 UTC
MongooseIM version: 3.7
Installed from: source
Erlang/OTP version: Erlang/OTP 21
Sending a one message in group:
`<body rid="2900050992" sid="54933ee7c8ca7c7f398f69b1cfc3827bfa0017f8" xmlns="http://jabber.org/protocol/httpbind"><message id="4562c104-266f-4b59-9da0-0430fc1d5aa8" to="channel-1610710499778@muclight.localhost" type="groupchat" xmlns="jabber:client"><body>test</body></message></body>`
There are messages in inbox and unread_count=3.
also comes 3 push notifications.

**Comment by DenysGonchar** [comment] 2021-02-26 08:53
Unread count field doesn't affect the number of push notifications. Do you receive one and the same push notification? Please show the content of that push notifications?

**Comment by krot3232** [comment] 2021-03-19 21:11
When there were 3 users in the group, then when sending a message, each of them received 3 the same notifications and inbox unread increased by 3.
The original data was not preserved, we updated the server to version 4.1 and  the error is gone. 
4.1 when launched, it issues:
`Erlang/OTP 21 [erts-10.3.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

when=2021-03-19T20:52:06.951730+00:00 level=notice pid=<0.258.0> at=: report="[{msg,\"Starting reporters with []\\n\"},{options,[]}]" label={error_logger,info_report}
16:52:06.978 [info] msg: "Starting reporters with []\n", options: []
16:52:07.432 [info] Application mnesia exited with reason: stopped
when=2021-03-19T20:52:07.432105+00:00 level=notice pid=<0.43.0> at=application_controller:info_exited/3:1941 report=[{application,mnesia},{exited,stopped},{type,permanent}] label={application_controller,exit}
when=2021-03-19T20:52:08.346701+00:00 level=warning what=cfg_validate_domain reason=nxdomain pid=<0.405.0> at=mongoose_config_validator:validate_domain_res/1:135 text="Couldn't resolve domain. It could cause issues with production installations" domain=pubsub.example.com
when=2021-03-19T20:52:08.390127+00:00 level=warning what=cfg_validate_domain reason=nxdomain pid=<0.405.0> at=mongoose_config_validator:validate_domain_res/1:135 text="Couldn't resolve domain. It could cause issues with production installations" domain=upload.example.com
when=2021-03-19T20:52:08.426204+00:00 level=warning what=cfg_validate_domain reason=nxdomain pid=<0.405.0> at=mongoose_config_validator:validate_domain_res/1:135 text="Couldn't resolve domain. It could cause issues with production installations" domain=muclight.example.com
when=2021-03-19T20:52:08.467791+00:00 level=warning what=cfg_validate_domain reason=nxdomain pid=<0.405.0> at=mongoose_config_validator:validate_domain_res/1:135 text="Couldn't resolve domain. It could cause issues with production installations" domain=muclight.example.com
when=2021-03-19T20:52:08.503937+00:00 level=warning what=cfg_validate_domain reason=nxdomain pid=<0.405.0> at=mongoose_config_validator:validate_domain_res/1:135 text="Couldn't resolve domain. It could cause issues with production installations" domain=pubsub.example.com
when=2021-03-19T20:52:08.557626+00:00 level=warning what=cfg_validate_domain reason=nxdomain pid=<0.405.0> at=mongoose_config_validator:validate_domain_res/1:135 text="Couldn't resolve domain. It could cause issues with production installations" domain=vjud.example.com
when=2021-03-19T20:52:08.845582+00:00 level=warning pid=<0.646.0> at=: unstructured_log="Warning 1287: '@@query_cache_type' is deprecated and will be removed in a future release.\
 in SET SESSION query_cache_type=1;`

If you write to yourself, then when you request to mam 2 messages: 
`SEND:  <message from="1145@localhost/test1616185534147" id="8bf685ae-4743-46fe-94ae-35ac13a4b467" to="1145@localhost" type="chat" xmlns="jabber:client"><body xmlns="jabber:client">1ZZZZZZZZZZZZZZZZZZ</body><origin-id id="8bf685ae-4743-46fe-94ae-35ac13a4b467" xmlns="urn:xmpp:sid:0"/></message>
RECV:  <message from="1145@localhost/test1616185534147" id="8bf685ae-4743-46fe-94ae-35ac13a4b467" to="1145@localhost" type="chat" xml:lang="en" xmlns="jabber:client"><body xmlns="jabber:client">1ZZZZZZZZZZZZZZZZZZ</body><origin-id id="8bf685ae-4743-46fe-94ae-35ac13a4b467" xmlns="urn:xmpp:sid:0"/><stanza-id by="1145@localhost" id="BFF9GBD7OBG1" xmlns="urn:xmpp:sid:0"/></message>

SEND:  <iq id="b1a13a82-5084-4a37-89ae-26395ceb3968:sendIQ" type="set" xmlns="jabber:client"><query xmlns="urn:xmpp:mam:2"><x type="submit" xmlns="jabber:x:data"><field type="hidden" var="FORM_TYPE"><value>urn:xmpp:mam:2</value></field><field var="with"><value>1145@localhost</value></field></x><set xmlns="http://jabber.org/protocol/rsm"><max>2</max><before></before></set></query></iq>

RECV:  <message from="1145@localhost" id="9c1c0409-d5e0-4b5b-bbc3-dcbf0521655a" to="1145@localhost/test1616185759389" xmlns="jabber:client"><result id="BFF9GBD6TP01" xmlns="urn:xmpp:mam:2"><forwarded xmlns="urn:xmpp:forward:0"><delay from="1145@localhost/test1616185534147" stamp="2021-03-19T20:25:03Z" xmlns="urn:xmpp:delay"/><message from="1145@localhost/test1616185534147" id="8bf685ae-4743-46fe-94ae-35ac13a4b467" to="1145@localhost" type="chat" xml:lang="en" xmlns="jabber:client"><body xmlns="jabber:client">1ZZZZZZZZZZZZZZZZZZ</body><origin-id id="8bf685ae-4743-46fe-94ae-35ac13a4b467" xmlns="urn:xmpp:sid:0"/></message></forwarded></result></message><message from="1145@localhost" id="01a93468-77ac-4c5e-b67e-d22b0f52e93e" to="1145@localhost/test1616185759389" xmlns="jabber:client"><result id="BFF9GBD7OBG1" xmlns="urn:xmpp:mam:2"><forwarded xmlns="urn:xmpp:forward:0"><delay from="1145@localhost/test1616185534147" stamp="2021-03-19T20:25:03Z" xmlns="urn:xmpp:delay"/><message from="1145@localhost/test1616185534147" id="8bf685ae-4743-46fe-94ae-35ac13a4b467" to="1145@localhost" type="chat" xml:lang="en" xmlns="jabber:client"><body xmlns="jabber:client">1ZZZZZZZZZZZZZZZZZZ</body><origin-id id="8bf685ae-4743-46fe-94ae-35ac13a4b467" xmlns="urn:xmpp:sid:0"/></message></forwarded></result></message><iq from="1145@localhost" id="b1a13a82-5084-4a37-89ae-26395ceb3968:sendIQ" to="1145@localhost/test1616185759389" type="result" xmlns="jabber:client"><fin xmlns="urn:xmpp:mam:2"><set xmlns="http://jabber.org/protocol/rsm"><first index="161">BFF9GBD6TP01</first><last>BFF9GBD7OBG1</last><count>163</count></set></fin></iq>`

**Comment by Neustradamus** [comment] 2021-09-21 01:01
Any news on it?

**Comment by DenysGonchar** [comment] 2021-09-23 08:31
The only thing I could do with this issue is just closing it. We cannot reproduce it as in original description:
* Inbox counter is increasing on incoming message processing. From the code perspective, I do not see any theoretical scenario that can lead to processing one message thrice. If it isn't sent 3 times, of course. 
* The only option how one device can receive 3 push notifications for just one message - there are 3 different [Push Service providers](https://esl.github.io/MongooseDocs/latest/tutorials/push-notifications/Push-notifications-client-side/) registered for one and the same device. Note the push service is identified by the user's bare JID, PubSub service JID (even if it's virtual one) and PubSub node name. MIM doesn't know anything about client devices, it just sends push notifications to all the registered providers.

As for the second comment, it's completely irrelevant to the original issue:
* The reported initialization warnings are not critical, MIM just informs you that some configured domains/subdomains are not DNS resolvable, however this is not critical if automatic XMPP federation is not expected.
* as for the duplicate of the message in mam:
   * that would be nice to have formatted XML logs:
```
<?xml version="1.0" encoding="UTF-8"?>
<some_tag>
   SEND:
   <message xmlns="jabber:client" from="1145@localhost/test1616185534147" id="8bf685ae-4743-46fe-94ae-35ac13a4b467" to="1145@localhost" type="chat">
      <body>1ZZZZZZZZZZZZZZZZZZ</body>
      <origin-id xmlns="urn:xmpp:sid:0" id="8bf685ae-4743-46fe-94ae-35ac13a4b467" />
   </message>
   RECV:
   <message xmlns="jabber:client" from="1145@localhost/test1616185534147" id="8bf685ae-4743-46fe-94ae-35ac13a4b467" to="1145@localhost" type="chat" xml:lang="en">
      <body>1ZZZZZZZZZZZZZZZZZZ</body>
      <origin-id xmlns="urn:xmpp:sid:0" id="8bf685ae-4743-46fe-94ae-35ac13a4b467" />
      <stanza-id xmlns="urn:xmpp:sid:0" by="1145@localhost" id="BFF9GBD7OBG1" />
   </message>
   SEND:
   <iq xmlns="jabber:client" id="b1a13a82-5084-4a37-89ae-26395ceb3968:sendIQ" type="set">
      <query xmlns="urn:xmpp:mam:2">
         <x xmlns="jabber:x:data" type="submit">
            <field type="hidden" var="FORM_TYPE">
               <value>urn:xmpp:mam:2</value>
            </field>
            <field var="with">
               <value>1145@localhost</value>
            </field>
         </x>
         <set xmlns="http://jabber.org/protocol/rsm">
            <max>2</max>
            <before />
         </set>
      </query>
   </iq>
   RECV:
   <message xmlns="jabber:client" from="1145@localhost" id="9c1c0409-d5e0-4b5b-bbc3-dcbf0521655a" to="1145@localhost/test1616185759389">
      <result xmlns="urn:xmpp:mam:2" id="BFF9GBD6TP01">
         <forwarded xmlns="urn:xmpp:forward:0">
            <delay xmlns="urn:xmpp:delay" from="1145@localhost/test1616185534147" stamp="2021-03-19T20:25:03Z" />
            <message xmlns="jabber:client" from="1145@localhost/test1616185534147" id="8bf685ae-4743-46fe-94ae-35ac13a4b467" to="1145@localhost" type="chat" xml:lang="en">
               <body>1ZZZZZZZZZZZZZZZZZZ</body>
               <origin-id xmlns="urn:xmpp:sid:0" id="8bf685ae-4743-46fe-94ae-35ac13a4b467" />
            </message>
         </forwarded>
      </result>
   </message>
   <message xmlns="jabber:client" from="1145@localhost" id="01a93468-77ac-4c5e-b67e-d22b0f52e93e" to="1145@localhost/test1616185759389">
      <result xmlns="urn:xmpp:mam:2" id="BFF9GBD7OBG1">
         <forwarded xmlns="urn:xmpp:forward:0">
            <delay xmlns="urn:xmpp:delay" from="1145@localhost/test1616185534147" stamp="2021-03-19T20:25:03Z" />
            <message xmlns="jabber:client" from="1145@localhost/test1616185534147" id="8bf685ae-4743-46fe-94ae-35ac13a4b467" to="1145@localhost" type="chat" xml:lang="en">
               <body>1ZZZZZZZZZZZZZZZZZZ</body>
               <origin-id xmlns="urn:xmpp:sid:0" id="8bf685ae-4743-46fe-94ae-35ac13a4b467" />
            </message>
         </forwarded>
      </result>
   </message>
   <iq xmlns="jabber:client" from="1145@localhost" id="b1a13a82-5084-4a37-89ae-26395ceb3968:sendIQ" to="1145@localhost/test1616185759389" type="result">
      <fin xmlns="urn:xmpp:mam:2">
         <set xmlns="http://jabber.org/protocol/rsm">
            <first index="161">BFF9GBD6TP01</first>
            <last>BFF9GBD7OBG1</last>
            <count>163</count>
         </set>
      </fin>
   </iq>
</some_tag>
```
    * the reason why it happens - the message is written independently into sender's and receiver's MAM archives. Notice that these 2 messages have different MAM ID's: `BFF9GBD7OBG1` and `BFF9GBD6TP01`. So it's kinda expected behavior. But I agree that we can and should eliminate this duplication, because sending message to yourself is quite popular solution for making notes in most of the modern messengers.

**Comment by DenysGonchar** [comment] 2021-09-23 09:18
we cannot reproduce this issue as in original description, reporter cannot provide any additional details/logs.

**Closed by DenysGonchar** 2021-09-23 09:18 UTC

**Comment by krot3232** [comment] 2021-09-28 16:25
The problem was solved. The error was not in mongooseim Our php backend duplicated users in the `muc_light_occupants` table he so thought that unique key (room_id, luser) muc_light_occupants, from this came a push duplicates.
Thank you!
