### ISSUE TITLE
Blocking IQ returns Privacy response

### ISSUE THREAD

**Issue by binhly** [esl/MongooseIM#864] opened 2016-06-18 08:06 UTC
MongooseIM version: (put the version) 1.6.2
Installed from: (source or pkg) - Source
Erlang/OTP version: (put the version)

Describe the issue.

When I send this:

```xml
<iq type="get" id="31096A4A-DE25-4602-B42A-3ADB381461E7">
<blocklist xmlns="urn:xmpp:blocking"></blocklist></iq>
```
I get back this:

```xml
<iq xmlns="jabber:client" from="pc5e6c4u0fvmqile" to="pc5e6c4u0fvmqile" id="31096A4A-DE25-4602-B42A-3ADB381461E7" type="result">
<query xmlns="jabber:iq:privacy"></query>
</iq>
```
I think I should be getting something like this:

```xml
<iq type='result' id='31096A4A-DE25-4602-B42A-3ADB381461E7'>
  <blocklist xmlns='urn:xmpp:blocking'/>
</iq>
```

**Comment by michalwski** [comment] 2016-06-20 07:58
Hi @binhly,

Thanks for reporting this. You are right, we're going to look in to this and fix.

**Comment by bartekgorny** [comment] 2016-06-20 08:56
binhly, your test case must be more specific. We have it all tested, and in the tests I send:
```
<iq type='get'>
  <blocklist xmlns='urn:xmpp:blocking'/>
</iq>
```
and I receive:
```
<iq from='alicE77.183115@localhost' to='alicE77.183115@localhost/res1' id='' type='result'>
  <blocklist xmlns='urn:xmpp:blocking'/>
</iq>
```
If you get a different result then you must be doing something differently, please tell me what so that I can reproduce the problem

**Comment by ludwikbukowski** [comment] 2016-06-20 10:57
The problem lies in mongooseim version. You're using 1.6.2 and this version doesn't support [XEP-0191: Blocking Command](https://xmpp.org/extensions/xep-0191.html) yet. Please, checkout the newest master in order to use that XEP :)

**Comment by binhly** [comment] 2016-06-21 07:36
Thanks guys.  I will checkout master and give it a try.

Question for you: I must enable the module right?

Currently in my ejabberd.cfg I have this for mod_privacy {mod_privacy, []},

Would I enable XEP 191 with something like this? {mod_blocking, []},

I just want to make sure so that I don't ask needless questions later.

Thank you for your responses.

**Comment by ludwikbukowski** [comment] 2016-06-21 07:49
Exactly. Module `mod_blocking` should be enabled in `ejabberd.cfg` file. The line below must be added to the module list:

`{mod_blocking, []}, `

Additionally, since the blocking module uses privacy lists as a backend, do not remove `mod_privacy` from the module list. **You should have both modules enabled.** So the config would look like:
```
  {mod_privacy, []},
  {mod_blocking, []},
```

However, it's already done by default in current master branch [1] hence actually you do not need to modify the config file in this case.

[1] https://github.com/esl/MongooseIM/blob/master/rel/files/ejabberd.cfg#L676

**Comment by bartekgorny** [comment] 2016-06-21 07:50
On 21/06/16 09:36, Binh Ly wrote:
> Thanks guys. I will checkout master and give it a try.
>
> Question for you: I must enable the module right?
>
> Currently in my ejabberd.cfg I have this for mod_privacy {mod_privacy, []},
>
> Would I enable XEP 191 with something like this? {mod_blocking, []},

Yes, exactly.

**Comment by michalwski** [comment] 2016-06-28 10:57
@binhly, Did you try 1.6.2? Does it work for you?

**Comment by binhly** [comment] 2016-06-29 07:35
@michalslaski Hello!  Sorry for the delayed response.  I was able to get the latest from master, build and run and got the expected result.

<iq type='get'>
  <blocklist xmlns='urn:xmpp:blocking'/>
</iq>

<iq from="binh@test.chat" type="result" to="binh@test.chat/iMac" id="">
<blocklist xmlns="urn:xmpp:blocking"/>
</iq>

Thank you all for your help and quick response.

**Comment by michalwski** [comment] 2016-06-29 07:48
Thanks, for the update. I'm closing the issue.

**Closed by michalwski** 2016-06-29 07:48 UTC
