### ISSUE TITLE
backend mysql for mod_muc possible?

### ISSUE THREAD

**Issue by slincloud** [esl/MongooseIM#1356] opened 2017-06-26 11:46 UTC
MongooseIM version: 6.4
Installed from: https://github.com/ppikula/mongooseim-docker
Erlang/OTP version: 1> erlang:system_info(otp_release). => "17"

Describe the issue:

Recently we have a lot of traffic on hour hosts and the tables "muc_rooms" and "muc_online_rooms" are killing mnesia on a usual basis.
In the 3 MySQL schema files from https://github.com/esl/MongooseIM/tree/master/apps/ejabberd/priv I can not find a table for the rooms. Is it even possible to use "{db_type, odbc}" in the configuration of mod_muc in mongooseim? 

If not, can anyone give a hint on what to do?

In ejabberd apparently this is what you do, but I do not see the option here: http://mongooseim.readthedocs.io/en/1.6.1/modules/mod_muc/

**Comment by fenek** [comment] 2017-06-26 11:48
Hi @slincloud 

It is a feature that's at the end of review process (https://github.com/esl/MongooseIM/pull/1311) and will be available in `master` soon.

**Comment by slincloud** [comment] 2017-06-26 11:53
Hey fenek,

Thanks for your reply. Any suggestions on what to do right now with that situation?

**Comment by fenek** [comment] 2017-06-26 11:58
Although this branch is a bit behind current master, you could try to build it from source and try it out. The alternative is to wait for 2.1.0 release. I'd love to have this feature merged before beta2 release but I can't promise it. :(

**Comment by fenek** [comment] 2017-06-26 12:15
I suspect that the main source of your problems is `muc_online_users` table. It is the most modified of MUC tables, given your use case. Most probably these rooms experience users joining and leaving frequently. In such case you could try to reduce this rate as much as possible, e.g. by using Stream Management, which keeps session open if user disconnects unexpectedly. You could also research MUC Light extension (http://mongooseim.readthedocs.io/en/latest/open-extensions/muc_light/), if your use case does not require precise presence tracking.

Can you please share what errors are you exactly observing in logs?

**Comment by slincloud** [comment] 2017-06-26 12:32
The errors in crash.log are not really that revealing (at least for me). Every some minutes there are entries like this 
`2017-06-26 12:20:02 =CRASH REPORT====
  crasher:
    initial call: gen:init_it/6
    pid: <0.12547.51>
    registered_name: []
    exception exit: {{process_limit,{max_queue,1272}},[{p1_fsm_old,terminate,7,[{file,"src/p1_fsm_old.erl"},{line,690}]},{p1_fsm_old,loop,10,[{file,"src/p1_fsm_old.erl"},{line,398}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
    ancestors: [ejabberd_c2s_sup,ejabberd_sup,<0.191.0>]
    messages: []
    links: [<0.388.0>]
    dictionary: [{'$internal_queue_len',0}]
    trap_exit: false
    status: running
    heap_size: 121536
    stack_size: 27
    reductions: 4189936
  neighbours:
2017-06-26 12:20:02 =SUPERVISOR REPORT====
     Supervisor: {local,ejabberd_c2s_sup}
     Context:    child_terminated
     Reason:     {process_limit,{max_queue,1272}}
     Offender:   [{pid,<0.12547.51>},{name,undefined},{mfargs,{ejabberd_c2s,start_link,undefined}},{restart_type,temporary},{shutdown,brutal_kill},{child_type,worker}]
`

Or, less often, like this 

`2017-06-26 11:05:06 =ERROR REPORT====
** State machine <0.25441.12> terminating
** Last event in was {xmlstreamelement,{xmlel,<<"response">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-sasl">>}],[]}}
** When State == wait_for_sasl_response
**      Data  == {state,{socket_state,gen_tcp,#Port<0.550800>,<0.25440.12>},ejabberd_socket,#Ref<0.0.173.238882>,false,"1304839518",{sasl_state,<<"jabber">>,<<"tnt-live-chat">>,<<>>,#Fun<ejabberd_c2s.2.88956365>,#Fun<ejabberd_c2s.3.88956365>,#Fun<ejabberd_c2s.4.88956365>,cyrsasl_digest,{state,5,"1032190319",<<"jid_1rc2d930aab-aa84-4bcc-996e-2a597f7126de_1497794835">>,<<>>,#Fun<ejabberd_c2s.2.88956365>,#Fun<ejabberd_c2s.4.88956365>,ejabberd_auth_odbc,<<"tnt-live-chat">>}},c2s,c2s_shaper,{false,0},false,false,false,[verify_none],false,undefined,<<>>,<<"tnt-live-chat">>,<<>>,undefined,{pres_t,0},{pres_f,0},{pres_a,0},{pres_i,0},[],undefined,undefined,undefined,false,{userlist,none,[],false},unknown,undefined,{{151,82,94,46},31756},[],"en",false,0,undefined,0,[],0,100,1,600,undefined,undefined}
** Reason for termination =
** {noproc,{gen_server,call,[<0.25440.12>,reset_stream]}}
2017-06-26 11:05:06 =CRASH REPORT====
  crasher:
    initial call: gen:init_it/6
    pid: <0.25441.12>
    registered_name: []
    exception exit: {{noproc,{gen_server,call,[<0.25440.12>,reset_stream]}},[{p1_fsm_old,terminate,7,[{file,"src/p1_fsm_old.erl"},{line,695}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
    ancestors: [ejabberd_c2s_sup,ejabberd_sup,<0.162.0>]
    messages: [{'$gen_event',closed},{'DOWN',#Ref<0.0.173.238882>,process,<0.25440.12>,normal}]
    links: [<0.367.0>]
    dictionary: [{'$internal_queue_len',0}]
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 6023
  neighbours:
2017-06-26 11:05:06 =SUPERVISOR REPORT====
     Supervisor: {local,ejabberd_c2s_sup}
     Context:    child_terminated
     Reason:     {noproc,{gen_server,call,[<0.25440.12>,reset_stream]}}
     Offender:   [{pid,<0.25441.12>},{name,undefined},{mfargs,{ejabberd_c2s,start_link,undefined}},{restart_type,temporary},{shutdown,brutal_kill},{child_type,worker}]
`


When I do mongooseimctl mnesia info I see many locks like this 
` {tid,340506,<6182.667.53>}}
Lock: {{muc_online_room,{<<"some-room-name">>,
                         <<"muc.our-domain">>}},
       write,`
and the nodes holding ram_copies or disk_copies are usually at 100% CPU constantly. In the mnesia info I see values like this

`muc_online_room: with 53317    records occupying 1367431  words of mem
mod_register_ip: with 0        records occupying 299      words of mem
s2s            : with 0        records occupying 299      words of mem
muc_registered : with 0        records occupying 299      words of mem
mam_host       : with 1        records occupying 316      words of mem
iq_response    : with 0        records occupying 299      words of mem
local_config   : with 13       records occupying 1028     words of mem
privacy        : with 0        records occupying 299      words of mem
acl            : with 1        records occupying 315      words of mem
muc_room       : with 12666    records occupying 2242617  words of mem
node           : with 5        records occupying 339      words of mem
route          : with 3        records occupying 411      words of mem
config         : with 32       records occupying 956      words of mem
sql_pool       : with 10       records occupying 439      words of mem
sm_session     : with 0        records occupying 299      words of mem
schema         : with 18       records occupying 2715     words of mem`

  - the numbers can get much higher at the mentioned tables though. And every other our so so one of the nodes jumps the gun and becomes unresponsive and has to get put manually back to clustering with comes with it's own set of problems (corrupted mnesia database etc)

Is there any more info I can provide?

**Comment by fenek** [comment] 2017-06-27 14:06
1. Which `.xlarge` machines are you using exactly?
1. Have you considered running MongooseIM directly on your VMs, without Docker? As far as I know, network layer in Docker sometimes has its moods.
1. What is your average user login/logout rate?
1. What are the values of metrics such as `[global, mod_muc, deep_hibernations]` and `[global, mod_muc, process_recreations]`?
1. Is there a pattern to when the nodes start failing? Only with traffic peak? Every X hours? Completely random?
1. Do some nodes fail more often than others?

**Comment by slincloud** [comment] 2017-06-27 15:23
1. c4xlarge on AWS
2. not yet considered, could be an idea
3. Quite high. Judging from the logs it should be around 1.2k logins per minute
4. I am not sure how to view them?
5. There are no real spikes in traffic. The errors I posted above occur around every 5 minutes or so, but this does not result in an outage every time. Every few hours one of the nodes stopped responding, because the docker container stopped or maybe just because of the 100% CPU load. "beam.smp" is the process showing the high load.
6. The ones holding disc_copies or ram_copies are the ones with the CPU load and the ones that fail more often

On another note, today I switched from clustered mode to a single c4.4xlarge machine, and so far it is looking good. Apparently the mnesia sync is what killed them. That would mean you could only run a chat of a size you are able to support on a single machine and avoid clustering alltogether  - at least for now.

Thank you for your help!

**Comment by slincloud** [comment] 2017-06-28 12:05
Ok, so, sadly the single node setup runs better but is not the cure. CPU usage creeps up and up and up until after some hours it is at 100%.
I am at a loss here. Do you have any ideas what could cause this?

**Comment by fenek** [comment] 2017-06-28 12:15
Can you please paste the output of a snippet below?

```Erlang
[ {Pid, MQL, [{dictionary, process_info(Pid, dictionary)} | Props]} || {Pid, MQL, Props} <- recon:proc_count(message_queue_len, 10) ].
```

This should be executed in Erlang console when CPU usage becomes definitely higher than it should be.

**Comment by slincloud** [comment] 2017-06-28 13:21
```
Eshell V6.4  (abort with ^G)
1> [ {Pid, MQL, [{dictionary, process_info(Pid, dictionary)} | Props]} || {Pid, MQL, Props} <- recon:proc_count(message_queue_len, 10) ].
** exception error: undefined function recon:proc_count/2
2>
```

**Comment by fenek** [comment] 2017-06-28 13:22
Please run it inside MongooseIM shell. :)

**Comment by slincloud** [comment] 2017-06-28 13:26
Sorry :) here:
```
(debug--mongooseim@mongooseim-1)1> [ {Pid, MQL, [{dictionary, process_info(Pid, dictionary)} | Props]} || {Pid, MQL, Props} <- recon:proc_count(message_queue_len, 10) ].
[{<0.34.0>,0,
  [{dictionary,{dictionary,[{'$ancestors',[kernel_sup,
                                           <0.10.0>]},
                            {'$initial_call',{supervisor,kernel,1}}]}},
   kernel_safe_sup,
   {current_function,{gen_server,loop,6}},
   {initial_call,{proc_lib,init_p,5}}]},
 {<0.33.0>,0,
  [{dictionary,{dictionary,[{'$ancestors',[kernel_sup,
                                           <0.10.0>]},
                            {'$initial_call',{kernel_config,init,1}}]}},
   {current_function,{gen_server,loop,6}},
   {initial_call,{proc_lib,init_p,5}}]},
 {<0.32.0>,0,
  [{dictionary,{dictionary,[{evaluator,<0.38.0>}]}},
   {current_function,{shell,shell_rep,4}},
   {initial_call,{erlang,apply,2}}]},
 {<0.31.0>,0,
  [{dictionary,{dictionary,[{encoding,latin1},
                            {read_mode,list},
                            {shell,<0.32.0>}]}},
   user,
   {current_function,{user,server_loop,2}},
   {initial_call,{erlang,apply,2}}]},
 {<0.29.0>,0,
  [{dictionary,{dictionary,[{'$ancestors',[kernel_sup,
                                           <0.10.0>]},
                            {'$initial_call',{supervisor_bridge,user_sup,1}}]}},
   {current_function,{gen_server,loop,6}},
   {initial_call,{proc_lib,init_p,5}}]},
 {<0.28.0>,0,
  [{dictionary,{dictionary,[{encoding,latin1}]}},
   standard_error,
   {current_function,{standard_error,server_loop,1}},
   {initial_call,{erlang,apply,2}}]},
 {<0.27.0>,0,
  [{dictionary,{dictionary,[{'$ancestors',[kernel_sup,
                                           <0.10.0>]},
                            {'$initial_call',{supervisor_bridge,standard_error,1}}]}},
   standard_error_sup,
   {current_function,{gen_server,loop,6}},
   {initial_call,{proc_lib,init_p,5}}]},
 {<0.26.0>,0,
  [{dictionary,{dictionary,[{any_native_code_loaded,false}]}},
   code_server,
   {current_function,{code_server,loop,1}},
   {initial_call,{erlang,apply,2}}]},
 {<0.25.0>,0,
  [{dictionary,{dictionary,[{'$ancestors',[kernel_sup,
                                           <0.10.0>]},
                            {'$initial_call',{file_server,init,1}}]}},
   file_server_2,
   {current_function,{gen_server,loop,6}},
   {initial_call,{proc_lib,init_p,5}}]},
 {<0.24.0>,0,
  [{dictionary,{dictionary,[{whereis_name,[undefined]},
                            {send,[undefined]},
                            {'$ancestors',[kernel_sup,<0.10.0>]},
                            {registered_names,[undefined]},
                            {'$initial_call',{global_group,init,1}}]}},
   global_group,
   {current_function,{gen_server,loop,6}},
   {initial_call,{proc_lib,init_p,5}}]}]
(debug--mongooseim@mongooseim-1)2>

```

**Comment by fenek** [comment] 2017-06-28 13:31
It looks a bit like a printout from idle VM. Where does this strange node name come from? (`debug--mongooseim`) Is it your normal node name for production VM? Do you open the shell via `(installation root)/bin/mongooseim debug`?

**Comment by slincloud** [comment] 2017-06-28 13:38
I started it with mongooseimctl debug. Sorry for being dumb here. How do I start the right one?

**Comment by fenek** [comment] 2017-06-28 13:46
Maybe it's something specific to Docker image... Since I use MongooseIM compiled from source on daily basis, I might not have spare time today to check the dockerized version.

I understand it's an urgent issue, so maybe you could contact our sales team, so you could get support faster, from an engineer assigned specifically to resolving your problem?

**Comment by slincloud** [comment] 2017-06-28 13:48
I will try that. Thank you for your effort!

**Comment by fenek** [comment] 2017-07-10 08:24
Hi @slincloud 

Anything new regarding this issue? :) If your problem is not resolved yet, I have more spare time now (since beta2 is out) and maybe I could help you.

**Comment by fenek** [comment] 2017-07-10 11:21
My colleague, @michalwski, suggested it may be caused by container not being started with TTY enabled (`-t` option in Docker). Can you please check if this parameter is enabled in your deployment scripts?

**Comment by fenek** [comment] 2018-06-26 16:54
Closing due to inactivity. Please reopen if the problem persists.

**Closed by fenek** 2018-06-26 16:54 UTC
