### ISSUE TITLE
While downgrading mongooseim from 3.7.0 to 3.60 users does not connect

### ISSUE THREAD

**Issue by jaspreet-android** [esl/MongooseIM#3073] opened 2021-04-02 17:31 UTC
MongooseIM version: 3.6.0
Installed from: source
Erlang/OTP version: OTP 22

When we try to downgrade mongooseim version from 3.7.0 to 3.6.0 then users are not able to connect, we get crash in the logs which says :

```
2021-04-02 21:11:14.409 [info] <0.1578.0>@mongoose_tcp_listener:accept_loop:81 (#Port<0.102>) Accepted connection {{10,10,7,33},59326} -> {{10,10,7,30},5222}
2021-04-02 21:11:14.783 [warning] <0.2006.0>@mongoose_scram:deserialize:166 Corrupted serialized SCRAM: <<"==MULTI_SCRAM==,10000,===SHA1===67ZA0DNdPZFFC6R18krYPg==|esYTGmJuRDjQePPxgWv/QOnQXhQ=|5DW15K2aWTgVPgThiIM7mULHbXg=,==SHA224==Fah4jz95iJzVVSor7pS4Fw==|qwGqpjNOEcN63IithG5fTzBYdh7VY/rhF4ZrqA==|YWNJ8TFgimC6Y7m/+Z/utWaZ188aKAqHBeRNkg==,==SHA256==+H5eGkEClBbs8QXJqU2dAA==|xnEckWflszPkz4Az6H/fUGD2Q6cfqO21FN43cs3pHsk=|D4C8nn0/oK3y1vPMwR0btUOwcJWrjtTXWwOLxTab2Qo=,==SHA384==jJiHp+dNvJIup6yJy1IYnQ==|fR141y4IdL5TxIxjEtQi/siCfTyEw34kD0Kz+NBqt2VC0jx+onC6k0x0x119a7Dg|vlPltGKMgabpbb+yiuGSyjoj7oIyO2b1F6scDLkbTsDZ41cmxNy7n38Qb4oEHq6O,==SHA512==VLPSVCWOYaZHSxxzwKwYiQ==|PYKO77N9I3pZ4rUBGU2PGdBF4ODDAKeSPZSJOxtAklkKMfYn47uqmNC8ussA+k2V1Zg6uigY88+0R9O+JfQC5A==|N1GgNXtlWmPedOKaUPvZph9lOCEN99QlNMiLdHmtyXcFppu6BuotrER9FitpYEuhG74cQTpzxEDQ87zGhM3w0A==">>
2021-04-02 21:11:14.783 [info] <0.2006.0>@ejabberd_c2s:handle_sasl_step:3283 ({socket_state,ejabberd_tls,{ejabberd_tls_socket,fast_tls,#Port<0.102>,{tlssock,#Port<0.102>,#Ref<0.4289873706.4067033089.171360>},[{ciphers,[84,76,83,118,49,46,50,58,84,76,83,118,49,46,51]},{protocol_options,[110,111,95,115,115,108,118,50,124,110,111,95,115,115,108,118,51,124,110,111,95,116,108,115,118,49,124,110,111,95,116,108,115,118,49,95,49]},verify_none,{certfile,[47,109,111,110,103,111,111,115,101,105,109,47,97,108,108,46,112,101,109]}],false},<0.2005.0>}) Failed authentication for 315fdd81-31f4-4b1f-85b4-d03d32b89e9e@localhost from IP 10.10.7.33 ({{10,10,7,33},59326})

```

In 3.7.0 we use 
{sasl_mechanisms, "{sasl_mechanisms, [cyrsasl_scram_sha1, cyrsasl_plain]}."}.

In 3.6.0 we use 
{sasl_mechanisms, "%%{sasl_mechanisms, [cyrsasl_scram, cyrsasl_plain]}."}.

**Comment by janciesla8818** [comment] 2021-04-06 07:45
Please note that since MongooseIM 3.7 there was a password format change. If I get it correctly, the new user was registered in 3.7 and then, after the downgrade, the user was not able to connect. Using newer password format in older versions is not supported hence, the authentication was not successful. 

In this scenario, the recommendation would be to use the version where the user was registered or remove and register the user again in MongooseIM 3.6.

For more details, please have a look at the migration guide https://esl.github.io/MongooseDocs/latest/migrations/3.6.0_3.7.0/ and SCRAM serialization fromat https://esl.github.io/MongooseDocs/latest/developers-guide/SCRAM-serialization/ sections.

**Comment by janciesla8818** [comment] 2021-04-06 07:46
Closing the issue, as this is expected behavior.

**Closed by janciesla8818** 2021-04-06 07:46 UTC

**Comment by jaspreet-android** [comment] 2021-04-06 09:16
Hi @janciesla8818 thanks for answering on the question, please see the question again while upgrade we did not change the scrum we used : cyrsasl_scram_sha1, and we are aware of the scrum changes in 3.7.0.

Also the user error I given above is not registered from 3.7.0 he was registered from 3.6.0 only and was able to login on 3.7.0 after upgrade but failed to login on 3.6.0 downgrade.

**Comment by janciesla8818** [comment] 2021-04-06 09:45
Hi @jaspreet-android,

The thing here is that the format of what is stored in the DB changed between versions 3.6 and 3.7 and this is important. 

Looking at the logs provided, it seems that either the passwords were migrated to the new format or the user was registered in 3.7.  In your logs the password entry that is in your DB starts with `<<"==MULTI_SCRAM==," ... ` which is the new password format. The old one was starting with `<<"==SCRAM==," ... `
https://esl.github.io/MongooseDocs/latest/developers-guide/SCRAM-serialization/

You have  `<<"==MULTI_SCRAM==," ... ` (new format) of user password details in your DB and it will not work with MongooseIM 3.6 as it is not aware of this new syntax. 

Due to this change, it's more challenging to move between those versions and the recommendation here would be to stick with 3.7 after you have the passwords in the new format.

**Comment by jaspreet-android** [comment] 2021-04-06 10:45
Thanks @janciesla8818 for the explanation, Our Idea is to upgrade only but we were checking the backup plan if anything goes wrong so it was our test. Now we know that it will be tuff, anyways thanks for the quick answers :)

**Comment by janciesla8818** [comment] 2021-04-06 11:30
For the migration, you can create a backup of the DB before the migration, with the old password formats. If something goes wrong, you can downgrade and connect to the backup DB.
