### ISSUE TITLE
muclight chat messages not getting when user is offline

### ISSUE THREAD

**Issue by sandy5487** [esl/MongooseIM#1566] opened 2017-11-13 15:33 UTC
MongooseIM version: 2.0.1
Installed from: pkg

I am not able to get the messages when a user is offline in muclight; but the users who are online are getting the messages.

this is my configuration if needed 

Please @fenek @ludwikbukowski help me to sort out

Thanks in advance

![screen shot 2017-11-13 at 9 00 30 pm](https://user-images.githubusercontent.com/14825242/32733606-c0459160-c8b5-11e7-8569-a845cbbd0e17.png)

**Comment by ludwikbukowski** [comment] 2017-11-13 15:35
`mod_offline` is not compatibile with MUC Light (which by the way was one of the assumptions)
Please use MAM to obtain offline messages from Muc Light

**Comment by sandy5487** [comment] 2017-11-13 17:19
how can I achieve this ?

**Comment by fenek** [comment] 2017-11-22 14:56
Hi @sandy5487 

First of all, you do not need to enable `mod_muc` when `mod_muc_light` is enabled. In fact, although they shouldn't collide in any way, we do not test that and cannot guarantee that both of these extensions can work side by side.

`mod_muc_log` applies only to `mod_muc` so may be disabled as well.

Enabling `mod_mam_muc` directly is not a recommended way now, as MAM implementation is very flexible and configuring it directly should be reserved only for advanced users. We have a proxy module `mod_mam_meta` which is much more user-friendly. Please check the documentation to learn how to use it: http://mongooseim.readthedocs.io/en/latest/modules/mod_mam/

**Comment by fenek** [comment] 2018-01-10 23:59
Hi @sandy5487 

Has my last comment helped you? If so, please close this issue. :)

**Comment by sandy5487** [comment] 2018-01-12 11:55
Hi @fenek 

thanks for the update.

**this is my latest configuration.**

```
   {mod_mam_meta, [
    %% Use ODBC backend (default)
   {backend, odbc},

    %% Do not store user preferences (default)
%   {user_prefs_store, false},
    %% Store user preferences in RDBMS
%   {user_prefs_store, odbc},
    %% Store user preferences in Mnesia (recommended).
    %% The preferences store will be called each time, as a message is routed.
    %% That is why Mnesia is better suited for this job.
%   {user_prefs_store, mnesia},

    %% Enables a pool of asynchronous writers. (default)
    %% Messages will be grouped together based on archive id.
%   {async_writer, true},

    %% Cache information about users (default)
%   {cache_users, true},

    %% Enable archivization for private messages (default)
%   {pm, [
      %% Top-level options can be overriden here if needed, for example:
%     {async_writer, false}
%   ]},

    %%
    %% Message Archive Management (MAM) for multi-user chats (MUC).
    %% Enable XEP-0313 for "muc.@HOST@".
    %%
   {muc, [
     {host, "muclight.@HOST@"}
      %% As with pm, top-level options can be overriden for MUC archive
   ]},
%
    %% Do not use a <stanza-id/> element (by default stanzaid is used)
%   no_stanzaid_element,
    %% Use <archived/> element (by default it is not used and not recommended)
%   add_archived_element
]},

       
```,

                                                                               
**after updating my configuration file with mod_mam_meta.**
I am getting this error in console.

```
2018-01-12 11:50:09.808 [error] <0.301.0>@ejabberd_config:describe_config_problem:307 The following lines from your configuration file might be relevant to the error: 
856:     %%
857:    {muc, [
858:      {host, "muclight.@HOST@"}
859:       %% As with pm, top-level options can be overriden for MUC archive
860:    ]},
861: %
862:     %% Do not use a <stanza-id/> element (by default stanzaid is used)
863: %   no_stanzaid_element,
864:     %% Use <archived/> element (by default it is not used and not recommended)
865: %   add_archived_element
866: ]},
867: 
868: 
869:   %%

2018-01-12 11:50:09.808 [error] <0.301.0>@ejabberd_config:get_plain_terms_file:198 Problem loading ejabberd config file /etc/mongooseim/ejabberd.cfg approximately in the line 866: syntax error before: ']'
Problem loading ejabberd config file /etc/mongooseim/ejabberd.cfg approximately in the line 866: syntax error before: ']'

Crash dump is being written to: erl_crash.dump...done
```

waiting for your reply.

**Comment by fenek** [comment] 2018-03-19 10:18
Hi @sandy5487 

Do you have any remaining configuration problems regarding MAM and MUC Light?

**Comment by fenek** [comment] 2018-06-26 16:46
Closing due to inactivity. Please reopen if the issue is still valid.

**Closed by fenek** 2018-06-26 16:46 UTC
